package hostutil

type hostCase struct {
	operation      string
	input          string
	boolOutput     *bool
	classification *HostClassification
}

func hostBool(value bool) *bool                                       { return &value }
func hostClassification(value HostClassification) *HostClassification { return &value }

var hostCases = []hostCase{
	{operation: "classifyHost", input: "localhostattacker.com", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "localhostattacker.com"})},
	{operation: "classifyHost", input: "notlocalhost", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "notlocalhost"})},
	{operation: "classifyHost", input: "localhost.evil.com", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "localhost.evil.com"})},
	{operation: "classifyHost", input: "example.com", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "example.com"})},
	{operation: "classifyHost", input: "api.example.com", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "api.example.com"})},
	{operation: "classifyHost", input: "tenant.localhost", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "tenant.localhost"})},
	{operation: "classifyHost", input: "app.foo.localhost", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "app.foo.localhost"})},
	{operation: "classifyHost", input: "my-app.localhost", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "my-app.localhost"})},
	{operation: "classifyHost", input: "metadata.google.internal", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "metadata.google.internal"})},
	{operation: "classifyHost", input: "metadata.goog", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "metadata.goog"})},
	{operation: "classifyHost", input: "metadata", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "metadata"})},
	{operation: "classifyHost", input: "instance-data", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "instance-data"})},
	{operation: "classifyHost", input: "instance-data.ec2.internal", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "instance-data.ec2.internal"})},
	{operation: "classifyHost", input: "localhost", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "localhost"})},
	{operation: "classifyHost", input: "localhost", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "localhost"})},
	{operation: "classifyHost", input: "9.255.255.255", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "9.255.255.255"})},
	{operation: "classifyHost", input: "11.0.0.0", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "11.0.0.0"})},
	{operation: "classifyHost", input: "172.15.255.255", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "172.15.255.255"})},
	{operation: "classifyHost", input: "172.32.0.0", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "172.32.0.0"})},
	{operation: "classifyHost", input: "192.167.255.255", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "192.167.255.255"})},
	{operation: "classifyHost", input: "192.169.0.0", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "192.169.0.0"})},
	{operation: "classifyHost", input: "100.63.255.255", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "100.63.255.255"})},
	{operation: "classifyHost", input: "100.128.0.0", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "100.128.0.0"})},
	{operation: "classifyHost", input: "10.0.0.1", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv4"), Canonical: "10.0.0.1"})},
	{operation: "classifyHost", input: "10.255.255.255", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv4"), Canonical: "10.255.255.255"})},
	{operation: "classifyHost", input: "172.16.0.1", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv4"), Canonical: "172.16.0.1"})},
	{operation: "classifyHost", input: "172.31.255.255", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv4"), Canonical: "172.31.255.255"})},
	{operation: "classifyHost", input: "192.168.0.1", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv4"), Canonical: "192.168.0.1"})},
	{operation: "classifyHost", input: "192.168.255.255", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv4"), Canonical: "192.168.255.255"})},
	{operation: "classifyHost", input: "198.18.0.1", classification: hostClassification(HostClassification{Kind: HostKind("benchmarking"), Literal: HostLiteral("ipv4"), Canonical: "198.18.0.1"})},
	{operation: "classifyHost", input: "198.19.255.255", classification: hostClassification(HostClassification{Kind: HostKind("benchmarking"), Literal: HostLiteral("ipv4"), Canonical: "198.19.255.255"})},
	{operation: "classifyHost", input: "255.255.255.255", classification: hostClassification(HostClassification{Kind: HostKind("broadcast"), Literal: HostLiteral("ipv4"), Canonical: "255.255.255.255"})},
	{operation: "classifyHost", input: "192.0.2.1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv4"), Canonical: "192.0.2.1"})},
	{operation: "classifyHost", input: "198.51.100.42", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv4"), Canonical: "198.51.100.42"})},
	{operation: "classifyHost", input: "203.0.113.99", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv4"), Canonical: "203.0.113.99"})},
	{operation: "classifyHost", input: "169.254.0.1", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv4"), Canonical: "169.254.0.1"})},
	{operation: "classifyHost", input: "169.254.169.254", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv4"), Canonical: "169.254.169.254"})},
	{operation: "classifyHost", input: "169.254.255.255", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv4"), Canonical: "169.254.255.255"})},
	{operation: "classifyHost", input: "127.0.0.1", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.1"})},
	{operation: "classifyHost", input: "127.0.0.0", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.0"})},
	{operation: "classifyHost", input: "127.255.255.255", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.255.255.255"})},
	{operation: "classifyHost", input: "127.42.42.42", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.42.42.42"})},
	{operation: "classifyHost", input: "224.0.0.1", classification: hostClassification(HostClassification{Kind: HostKind("multicast"), Literal: HostLiteral("ipv4"), Canonical: "224.0.0.1"})},
	{operation: "classifyHost", input: "239.255.255.255", classification: hostClassification(HostClassification{Kind: HostKind("multicast"), Literal: HostLiteral("ipv4"), Canonical: "239.255.255.255"})},
	{operation: "classifyHost", input: "8.8.8.8", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "8.8.8.8"})},
	{operation: "classifyHost", input: "1.1.1.1", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "1.1.1.1"})},
	{operation: "classifyHost", input: "142.250.80.46", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv4"), Canonical: "142.250.80.46"})},
	{operation: "classifyHost", input: "0.0.0.1", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv4"), Canonical: "0.0.0.1"})},
	{operation: "classifyHost", input: "240.0.0.1", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv4"), Canonical: "240.0.0.1"})},
	{operation: "classifyHost", input: "254.255.255.254", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv4"), Canonical: "254.255.255.254"})},
	{operation: "classifyHost", input: "100.64.0.1", classification: hostClassification(HostClassification{Kind: HostKind("sharedAddressSpace"), Literal: HostLiteral("ipv4"), Canonical: "100.64.0.1"})},
	{operation: "classifyHost", input: "100.127.255.255", classification: hostClassification(HostClassification{Kind: HostKind("sharedAddressSpace"), Literal: HostLiteral("ipv4"), Canonical: "100.127.255.255"})},
	{operation: "classifyHost", input: "0.0.0.0", classification: hostClassification(HostClassification{Kind: HostKind("unspecified"), Literal: HostLiteral("ipv4"), Canonical: "0.0.0.0"})},
	{operation: "classifyHost", input: "::ffff:169.254.169.254", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv4"), Canonical: "169.254.169.254"})},
	{operation: "classifyHost", input: "::ffff:127.0.0.1", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.1"})},
	{operation: "classifyHost", input: "0:0:0:0:0:ffff:192.0.2.1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv4"), Canonical: "192.0.2.1"})},
	{operation: "classifyHost", input: "::ffff:c000:0201", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv4"), Canonical: "192.0.2.1"})},
	{operation: "classifyHost", input: "2001:2::", classification: hostClassification(HostClassification{Kind: HostKind("benchmarking"), Literal: HostLiteral("ipv6"), Canonical: "2001:0002:0000:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "2001:2::1", classification: hostClassification(HostClassification{Kind: HostKind("benchmarking"), Literal: HostLiteral("ipv6"), Canonical: "2001:0002:0000:0000:0000:0000:0000:0001"})},
	{operation: "isPublicRoutableHost", input: "2001:2::1", boolOutput: hostBool(false)},
	{operation: "classifyHost", input: "3fff::", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "3fff:0000:0000:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "3fff:0fff::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "3fff:0fff:0000:0000:0000:0000:0000:0001"})},
	{operation: "isPublicRoutableHost", input: "3fff::", boolOutput: hostBool(false)},
	{operation: "classifyHost", input: "5f00::", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "5f00:0000:0000:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "5f00:abcd::1", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "5f00:abcd:0000:0000:0000:0000:0000:0001"})},
	{operation: "isPublicRoutableHost", input: "5f00::", boolOutput: hostBool(false)},
	{operation: "classifyHost", input: "64:ff9b:1::", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "0064:ff9b:0001:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "64:ff9b:1::a9fe:a9fe", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "0064:ff9b:0001:0000:0000:0000:a9fe:a9fe"})},
	{operation: "isPublicRoutableHost", input: "64:ff9b:1::", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "2001:20::1", boolOutput: hostBool(true)},
	{operation: "classifyHost", input: "2001:2:1::", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv6"), Canonical: "2001:0002:0001:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "2002:7f00:0001::", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "2002:7f00:0001:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "2002:a9fe:a9fe::", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "2002:a9fe:a9fe:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "2002:0a00:0001::", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "2002:0a00:0001:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "64:ff9b::7f00:1", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "0064:ff9b:0000:0000:0000:0000:7f00:0001"})},
	{operation: "classifyHost", input: "64:ff9b::a9fe:a9fe", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "0064:ff9b:0000:0000:0000:0000:a9fe:a9fe"})},
	{operation: "classifyHost", input: "64:ff9b::0a00:1", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "0064:ff9b:0000:0000:0000:0000:0a00:0001"})},
	{operation: "classifyHost", input: "64:ff9b::", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "0064:ff9b:0000:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "2001:0:0:0:0:0:80ff:fffe", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "2001:0000:0000:0000:0000:0000:80ff:fffe"})},
	{operation: "classifyHost", input: "2001:0:0:0:0:0:5601:5601", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("ipv6"), Canonical: "2001:0000:0000:0000:0000:0000:5601:5601"})},
	{operation: "classifyHost", input: "2002:2606:4700::", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv6"), Canonical: "2002:2606:4700:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "fec0::1", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv6"), Canonical: "fec0:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "::1", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2001:db8::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2001:db8::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2001:0db8:abcd::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:abcd:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "fe80::1", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "fe80:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "febf::1", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "febf:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "::1", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "0:0:0:0:0:0:0:1", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "0000:0000:0000:0000:0000:0000:0000:0001", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "ff00::1", classification: hostClassification(HostClassification{Kind: HostKind("multicast"), Literal: HostLiteral("ipv6"), Canonical: "ff00:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "ff02::1", classification: hostClassification(HostClassification{Kind: HostKind("multicast"), Literal: HostLiteral("ipv6"), Canonical: "ff02:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2606:4700:4700::1111", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv6"), Canonical: "2606:4700:4700:0000:0000:0000:0000:1111"})},
	{operation: "classifyHost", input: "2a00:1450:4001:828::200e", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("ipv6"), Canonical: "2a00:1450:4001:0828:0000:0000:0000:200e"})},
	{operation: "classifyHost", input: "fc00::1", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv6"), Canonical: "fc00:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "fd00::1", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv6"), Canonical: "fd00:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "fdff::1", classification: hostClassification(HostClassification{Kind: HostKind("private"), Literal: HostLiteral("ipv6"), Canonical: "fdff:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "::", classification: hostClassification(HostClassification{Kind: HostKind("unspecified"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "0:0:0:0:0:0:0:0", classification: hostClassification(HostClassification{Kind: HostKind("unspecified"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0000"})},
	{operation: "classifyHost", input: "::1", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "fe80::1", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "fe80:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "LOCALHOST", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "localhost"})},
	{operation: "classifyHost", input: "Example.COM", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "example.com"})},
	{operation: "classifyHost", input: "2001:DB8::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("fqdn"), Canonical: ""})},
	{operation: "classifyHost", input: "   ", classification: hostClassification(HostClassification{Kind: HostKind("reserved"), Literal: HostLiteral("fqdn"), Canonical: ""})},
	{operation: "isPublicRoutableHost", input: "", boolOutput: hostBool(false)},
	{operation: "isLoopbackHost", input: "", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "", boolOutput: hostBool(false)},
	{operation: "classifyHost", input: "fe80::1%eth0", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "fe80:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "[fe80::1%en0]:443", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "fe80:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "[::1]", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "[::1]", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "localhost:3000", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "localhost"})},
	{operation: "classifyHost", input: "example.com:443", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "example.com"})},
	{operation: "classifyHost", input: "127.0.0.1:3000", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.1"})},
	{operation: "classifyHost", input: "127.0.0.1:3000", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.1"})},
	{operation: "classifyHost", input: "[::1]:8080", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv6"), Canonical: "0000:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "[fe80::1]:443", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "fe80:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "localhost.", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "localhost"})},
	{operation: "classifyHost", input: "tenant.localhost.", classification: hostClassification(HostClassification{Kind: HostKind("localhost"), Literal: HostLiteral("fqdn"), Canonical: "tenant.localhost"})},
	{operation: "classifyHost", input: "metadata.google.internal.", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "metadata.google.internal"})},
	{operation: "classifyHost", input: "instance-data.ec2.internal.", classification: hostClassification(HostClassification{Kind: HostKind("cloudMetadata"), Literal: HostLiteral("fqdn"), Canonical: "instance-data.ec2.internal"})},
	{operation: "classifyHost", input: "127.0.0.1.", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.1"})},
	{operation: "classifyHost", input: "example.com.", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "example.com"})},
	{operation: "classifyHost", input: "  127.0.0.1  ", classification: hostClassification(HostClassification{Kind: HostKind("loopback"), Literal: HostLiteral("ipv4"), Canonical: "127.0.0.1"})},
	{operation: "classifyHost", input: "2001:db8::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2001:DB8::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2001:0db8::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "2001:db8:0::1", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "[2001:db8::1]", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "[2001:db8::1]:443", classification: hostClassification(HostClassification{Kind: HostKind("documentation"), Literal: HostLiteral("ipv6"), Canonical: "2001:0db8:0000:0000:0000:0000:0000:0001"})},
	{operation: "classifyHost", input: "evil-localhost.com", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "evil-localhost.com"})},
	{operation: "classifyHost", input: "localhost.attacker.com", classification: hostClassification(HostClassification{Kind: HostKind("public"), Literal: HostLiteral("fqdn"), Canonical: "localhost.attacker.com"})},
	{operation: "isPublicRoutableHost", input: "localhost.attacker.com", boolOutput: hostBool(true)},
	{operation: "isLoopbackHost", input: "0.0.0.0", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "0.0.0.0", boolOutput: hostBool(false)},
	{operation: "classifyHost", input: "0.0.0.0", classification: hostClassification(HostClassification{Kind: HostKind("unspecified"), Literal: HostLiteral("ipv4"), Canonical: "0.0.0.0"})},
	{operation: "isPublicRoutableHost", input: "169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "::ffff:169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "::FFFF:169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "0:0:0:0:0:ffff:169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "2002:7f00:0001::", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "2002:a9fe:a9fe::", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "64:ff9b::7f00:1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "64:ff9b::a9fe:a9fe", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "2001:0:0:0:0:0:80ff:fffe", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "2002:7f00:0001::", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "64:ff9b::7f00:1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "metadata.google.internal.", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "instance-data.ec2.internal.", boolOutput: hostBool(false)},
	{operation: "isLoopbackHost", input: "localhost.", boolOutput: hostBool(true)},
	{operation: "isLoopbackHost", input: "tenant.localhost.", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "127.0.0.1.", boolOutput: hostBool(true)},
	{operation: "isPublicRoutableHost", input: "::ffff:a9fe:a9fe", boolOutput: hostBool(false)},
	{operation: "classifyHost", input: "fe80::1%evil.com", classification: hostClassification(HostClassification{Kind: HostKind("linkLocal"), Literal: HostLiteral("ipv6"), Canonical: "fe80:0000:0000:0000:0000:0000:0000:0001"})},
	{operation: "isLoopbackHost", input: "0.0.0.0", boolOutput: hostBool(false)},
	{operation: "isLoopbackHost", input: "10.0.0.1", boolOutput: hostBool(false)},
	{operation: "isLoopbackHost", input: "example.com", boolOutput: hostBool(false)},
	{operation: "isLoopbackHost", input: "localhostattacker.com", boolOutput: hostBool(false)},
	{operation: "isLoopbackHost", input: "127.0.0.1", boolOutput: hostBool(true)},
	{operation: "isLoopbackHost", input: "::1", boolOutput: hostBool(true)},
	{operation: "isLoopbackHost", input: "localhost", boolOutput: hostBool(true)},
	{operation: "isLoopbackHost", input: "tenant.localhost", boolOutput: hostBool(true)},
	{operation: "isLoopbackHost", input: "tenant-a.localhost:3000", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "0.0.0.0", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "localhost", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "tenant.localhost", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "10.0.0.1", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "192.168.1.1", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "fe80::1", boolOutput: hostBool(false)},
	{operation: "isLoopbackIP", input: "127.0.0.1", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "127.5.42.1", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "127.0.0.1:3000", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "::1", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "[::1]", boolOutput: hostBool(true)},
	{operation: "isLoopbackIP", input: "[::1]:8080", boolOutput: hostBool(true)},
	{operation: "isPublicRoutableHost", input: "127.0.0.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "::1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "localhost", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "tenant.localhost", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "::ffff:127.0.0.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "255.255.255.255", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "224.0.0.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "ff00::1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "metadata.google.internal", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "metadata.goog", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "instance-data.ec2.internal", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "192.0.2.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "198.51.100.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "2001:db8::1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "198.18.0.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "::ffff:169.254.169.254", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "fe80::1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "10.0.0.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "172.16.0.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "192.168.1.1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "fc00::1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "fd00::1", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "0.0.0.0", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "::", boolOutput: hostBool(false)},
	{operation: "isPublicRoutableHost", input: "example.com", boolOutput: hostBool(true)},
	{operation: "isPublicRoutableHost", input: "api.example.com", boolOutput: hostBool(true)},
	{operation: "isPublicRoutableHost", input: "8.8.8.8", boolOutput: hostBool(true)},
	{operation: "isPublicRoutableHost", input: "2606:4700:4700::1111", boolOutput: hostBool(true)},
}
