// Code generated by go generate; DO NOT EDIT.

package singleauth

import (
	"context"
	"database/sql"
	"net/http"

	core "github.com/pers0na2dev/single-auth/core"
	"github.com/pers0na2dev/single-auth/core/engine"
	"github.com/pers0na2dev/single-auth/core/model"
	"github.com/pers0na2dev/single-auth/security/cookies"
)

// Types exported by the core runtime.
type APIError = core.APIError

type APIErrorOptions = core.APIErrorOptions

type AccessTokenResult = core.AccessTokenResult

type Account = core.Account

type AccountInfoInput = core.AccountInfoInput

type AccountInfoResult = core.AccountInfoResult

// AccountLinkingOptions configures built-in account linking and unlinking.
type AccountLinkingOptions = core.AccountLinkingOptions

// AccountOptions configures provider account persistence and linking.
type AccountOptions = core.AccountOptions

type AccountTokenInput = core.AccountTokenInput

// AdvancedOptions contains security- and transport-sensitive settings.
type AdvancedOptions = core.AdvancedOptions

// AnyKeyShape represents an unconstrained any-shaped object. It deliberately
// reports no statically known required keys.
type AnyKeyShape = core.AnyKeyShape

// Auth is an immutable upstream implementation-compatible runtime. It is safe for
// concurrent HTTP and direct API calls.
type Auth = core.Auth

// AuthContext exposes the initialized full-mode adapter and migration
// capability. It is an immutable snapshot.
type AuthContext = core.AuthContext

// AuthContextAdapterConfig is the Go counterpart of upstream implementation's adapter
// factory metadata.
type AuthContextAdapterConfig = core.AuthContextAdapterConfig

// AuthContextAdapterOptions describes the detected database dialect and the
// adapter factory that was selected for it.
type AuthContextAdapterOptions = core.AuthContextAdapterOptions

// AuthCookie describes one request-scoped upstream implementation cookie declaration.
// Attributes is copied when the context is created and whenever it is read.
type AuthCookie = core.AuthCookie

type AuthenticatedInput = core.AuthenticatedInput

// BackgroundRunner receives non-critical work. A nil runner executes work
// synchronously, matching upstream implementation's server fallback.
type BackgroundRunner = core.BackgroundRunner

// BaseErrorCodes is the statically typed core error-code subset used by type
// contracts. Values retain the public ErrorCode type instead of widening to
// string or any.
type BaseErrorCodes = core.BaseErrorCodes

// ChangeEmailConfirmationMessage is delivered to the current address before
// the new address is verified in the two-step flow.
type ChangeEmailConfirmationMessage = core.ChangeEmailConfirmationMessage

type ChangeEmailInput = core.ChangeEmailInput

type ChangeEmailOptions = core.ChangeEmailOptions

type ChangePasswordInput = core.ChangePasswordInput

type ChangePasswordResult = core.ChangePasswordResult

// CookieCacheLookupOptions controls the public session-data cookie reader.
// ResolveVersion is the Go equivalent of upstream implementation's synchronous or async
// version callback; it takes precedence over Version when non-nil.
type CookieCacheLookupOptions = core.CookieCacheLookupOptions

// CookieCacheOptions configures upstream implementation's session-data cookie.
type CookieCacheOptions = core.CookieCacheOptions

// CookieHeaderGetter is implemented by net/http.Header and by header shims
// from other runtimes. It keeps GetSessionCookie usable across realm or wrapper
// boundaries without relying on a concrete header type.
type CookieHeaderGetter = core.CookieHeaderGetter

// CookieOverride customizes one upstream implementation cookie. Attribute pointers retain
// the distinction between an omitted override and an explicit false value.
type CookieOverride = core.CookieOverride

// CrossSubDomainCookieOptions shares auth cookies across subdomains. When
// Domain is empty, a static base URL supplies its hostname; dynamic base URLs
// resolve it from each allowed incoming request.
type CrossSubDomainCookieOptions = core.CrossSubDomainCookieOptions

// DBFieldsDecoder converts a model's lossless dynamic field map into the
// caller's static Go representation. upstream implementation's TypeScript definitions can
// intersect configured and plugin fields into the base model automatically;
// Go callers provide the corresponding concrete Additional type and decoder.
type DBFieldsDecoder[Additional any] = core.DBFieldsDecoder[Additional]

type DatabaseAfterHook = core.DatabaseAfterHook

type DatabaseBeforeHook = core.DatabaseBeforeHook

// DatabaseHookContext describes one upstream implementation database lifecycle callback.
// Endpoint is nil when an adapter operation is initiated outside dispatch.
type DatabaseHookContext = core.DatabaseHookContext

// DatabaseHookResult is the Go equivalent of upstream implementation's false or
// {data: ...} before-hook result. Data is merged over the current write.
type DatabaseHookResult = core.DatabaseHookResult

// DatabaseHooks maps canonical model names to create/update/delete lifecycle
// callbacks. Core and plugin models use the same hook machinery.
type DatabaseHooks = core.DatabaseHooks

type DatabaseModelHooks = core.DatabaseModelHooks

type DatabaseOperationHooks = core.DatabaseOperationHooks

type DeleteAccountMessage = core.DeleteAccountMessage

type DeleteUserCallbackInput = core.DeleteUserCallbackInput

type DeleteUserCallbackResult = core.DeleteUserCallbackResult

type DeleteUserInput = core.DeleteUserInput

type DeleteUserOptions = core.DeleteUserOptions

// DirectAPI is the typed façade over Auth.Invoke. It uses the exact same
// endpoint handlers and before/after hooks as HTTP dispatch.
type DirectAPI = core.DirectAPI

// DirectCallInput is the escape hatch for core and plugin endpoints that do
// not yet have a dedicated typed convenience method. It still runs the exact
// endpoint and before/after-hook pipeline used by all typed methods.
type DirectCallInput = core.DirectCallInput

// DirectCallResult preserves both the transport-neutral response (including
// Set-Cookie and Location) and its decoded JSON value.
type DirectCallResult = core.DirectCallResult

type DirectInput = core.DirectInput

// DirectResultDecoder turns the production DirectCallResult into a concrete
// caller-facing output type.
type DirectResultDecoder[Output any] = core.DirectResultDecoder[Output]

// DynamicBaseURLOptions resolves the public auth URL from each request while
// constraining the host to an explicit allowlist. Protocol accepts "http",
// "https", or "auto"; an empty value defaults to HTTPS and also permits HTTP
// for loopback hosts, matching upstream implementation's development behavior.
type DynamicBaseURLOptions = core.DynamicBaseURLOptions

// EmailAndPasswordOptions configures the built-in credential endpoints.
type EmailAndPasswordOptions = core.EmailAndPasswordOptions

// EmailVerificationMessage contains the exact data passed to the email hook.
type EmailVerificationMessage = core.EmailVerificationMessage

// EmailVerificationOptions configures verification mail and token behavior.
type EmailVerificationOptions = core.EmailVerificationOptions

type Endpoint = core.Endpoint

// ErrorCode is a stable upstream implementation API error identifier.
type ErrorCode = core.ErrorCode

type GetSessionInput = core.GetSessionInput

// IDGenerator returns a upstream implementation identifier. The bool is false when the
// backing database must generate the identifier itself.
type IDGenerator = core.IDGenerator

// InternalAdapter is the Go counterpart of upstream implementation's internalAdapter.
// It keeps lifecycle hooks, secondary-storage behavior, identifier hashing,
// and transaction scoping above the raw storage.Adapter contract.
type InternalAdapter = core.InternalAdapter

// InternalOAuthUser is the user/account pair created by CreateOAuthUser.
type InternalOAuthUser = core.InternalOAuthUser

// InternalSession is the joined session/user value returned by FindSession
// and FindSessions.
type InternalSession = core.InternalSession

// InternalSessionCreateOptions represents upstream implementation's optional
// dontRememberMe, override, and overrideAll createSession arguments.
type InternalSessionCreateOptions = core.InternalSessionCreateOptions

// KnownPluginPresence is the true literal marker returned for a plugin whose
// position and type are known at compile time. Dynamic plugin IDs continue to
// return an ordinary bool through TypedPluginContext2.HasPlugin.
type KnownPluginPresence = core.KnownPluginPresence

type LinkSocialAccountInput = core.LinkSocialAccountInput

type LinkSocialAccountResult = core.LinkSocialAccountResult

type ListSessionsInput = core.ListSessionsInput

type ListSessionsResult = core.ListSessionsResult

type ListUserAccountsInput = core.ListUserAccountsInput

type ListUserAccountsResult = core.ListUserAccountsResult

type ListedAccount = core.ListedAccount

// MinimalAuth is the upstream implementation-compatible minimal runtime. It embeds the
// regular Go runtime while keeping the minimal entry point's migration and
// raw-connection constraints explicit.
type MinimalAuth = core.MinimalAuth

// MinimalContext exposes the adapter selected by the minimal initializer.
// DatabaseType is always "unknown" because minimal mode accepts an already
// configured storage adapter and does not perform database detection.
type MinimalContext = core.MinimalContext

// NoAdditionalFields is the explicit Go representation of a upstream implementation model
// with no configured or plugin-contributed fields. Go cannot intersect object
// types, so TypedUser and TypedSession retain additional fields in a generic
// slot whose empty form is this zero-sized type.
type NoAdditionalFields = core.NoAdditionalFields

// NoBody is the compile-time input for an endpoint override that deliberately
// removes the base endpoint's request body contract.
type NoBody = core.NoBody

type OAuthCallbackInput = core.OAuthCallbackInput

type OptionalKeyShape[Fields any] = core.OptionalKeyShape[Fields]

// Options is the immutable configuration snapshot consumed by New.
//
// Engine-level extension points are intentionally public so plugin packages
// can depend on focused contracts without creating a cycle through the
// canonical core runtime.
type Options = core.Options

// PasswordOptions configures credential hashing and validation. Nil functions
// use upstream implementation's scrypt implementation from package crypto.
type PasswordOptions = core.PasswordOptions

type PasswordResetCallbackInput = core.PasswordResetCallbackInput

// PasswordResetMessage contains the reset link delivered by the configured
// mail hook.
type PasswordResetMessage = core.PasswordResetMessage

type Plugin = core.Plugin

// PluginAPIs2 composes differently shaped plugin APIs without losing either
// concrete type. TypeScript flattens plugin endpoints into one object; Go keeps
// each collision-free API in an explicit slot.
type PluginAPIs2[First, Second any] = core.PluginAPIs2[First, Second]

// PluginFactory delays runtime-dependent plugin construction until New has
// created the final adapter, schema, cookie configuration, and core services.
// Schema must be deterministic and must describe every model used by Build.
type PluginFactory = core.PluginFactory

// PluginHost is the typed dependency surface supplied to PluginFactory.Build.
// Every callback enters the same root persistence, cookie, security, and
// background-work semantics as core endpoints.
type PluginHost = core.PluginHost

// PluginOAuthState is the generated CSRF state and PKCE verifier supplied to
// the provider authorization URL builder.
type PluginOAuthState = core.PluginOAuthState

// PluginOAuthStateData is the validated, single-use OAuth state exposed to
// protocol plugins. AdditionalData contains only plugin-owned fields that were
// persisted alongside the root callback, error, signup, and PKCE values.
type PluginOAuthStateData = core.PluginOAuthStateData

// PluginOAuthStateError is returned after a state lookup, cookie binding, or
// atomic consume failure. Code is safe to expose as an OAuth redirect error;
// ErrorURL is populated only when it came from already-validated state.
type PluginOAuthStateError = core.PluginOAuthStateError

// PluginOAuthStateInput is the transport-neutral input used by plugins that
// start a regular upstream implementation OAuth flow. AdditionalData is persisted in the
// same state record/cookie as core social sign-in after the caller has removed
// keys reserved by the state protocol.
type PluginOAuthStateInput = core.PluginOAuthStateInput

// PluginOAuthUserInput delegates identity/account resolution to the same
// implementation used by redirect social sign-in. Provider may be an
// ephemeral provider descriptor for protocol plugins such as One Tap that can
// operate without a configured redirect provider.
type PluginOAuthUserInput = core.PluginOAuthUserInput

// PluginOAuthUserResult carries the created session/user pair and the
// user-facing OAuth linking error that upstream returns separately from
// internal failures.
type PluginOAuthUserResult = core.PluginOAuthUserResult

// PluginPasswordHash is the request-aware password hash function exposed to
// plugin factories. Context is nil for non-endpoint use; wrappers must then
// behave as if no route path were active.
type PluginPasswordHash = core.PluginPasswordHash

// PluginPasswordHashWrapper decorates the hash function installed by prior
// factories. Factories are applied in declaration order, so the latest wrapper
// becomes the outermost one, matching upstream implementation init context composition.
type PluginPasswordHashWrapper = core.PluginPasswordHashWrapper

// PluginSessionMode selects the host's regular, authoritative, or fresh
// session policy.
type PluginSessionMode = core.PluginSessionMode

// PluginSessionState is the logical session/user pair shared with plugins.
type PluginSessionState = core.PluginSessionState

type ProviderUser = core.ProviderUser

type RateLimit = core.RateLimit

// RateLimitOptions configures the built-in request limiter. Window and Max
// are the default rule. Storage accepts "memory", "database", or
// "secondary-storage"; CustomStorage takes precedence when present.
type RateLimitOptions = core.RateLimitOptions

type RedirectResult = core.RedirectResult

type RefreshTokenResult = core.RefreshTokenResult

type Request = core.Request

// RequestAuthContext is the request-local counterpart of upstream implementation's
// AuthContext. It exposes the resolved public URL, the resolved option
// snapshot, trusted origins, cookie declarations, and the internal adapter to
// hooks and plugin endpoints without mutating the shared Auth runtime.
type RequestAuthContext = core.RequestAuthContext

// RequestAuthCookies contains the core cookie declarations available to an
// endpoint for the current request. Dynamic base URLs may produce a different
// Domain for every request.
type RequestAuthCookies = core.RequestAuthCookies

type RequestPasswordResetInput = core.RequestPasswordResetInput

// RequiredKeyShape and OptionalKeyShape retain the caller's field shape while
// explicitly recording whether its keys are required or optional.
type RequiredKeyShape[Fields any] = core.RequiredKeyShape[Fields]

type RequiredKeysAbsent = core.RequiredKeysAbsent

// RequiredKeysPresent and RequiredKeysAbsent are distinct compile-time result
// types. upstream implementation computes this distinction structurally; Go callers use an
// explicit shape wrapper because the language has no optional object keys.
type RequiredKeysPresent = core.RequiredKeysPresent

// RequiredKeysResult is the closed result set for RequiredKeysOf.
type RequiredKeysResult = core.RequiredKeysResult

type ResetPasswordInput = core.ResetPasswordInput

type Response = core.Response

type RevokeSessionInput = core.RevokeSessionInput

// SecondaryGetAndDeleter provides cross-process atomic consumption for
// single-use verification values.
type SecondaryGetAndDeleter = core.SecondaryGetAndDeleter

// SecondaryStorage is upstream implementation's string-valued session, verification, and
// rate-limit storage contract.
type SecondaryStorage = core.SecondaryStorage

// SecondaryValueGetAndDeleter provides atomic consumption for an
// object-valued secondary store.
type SecondaryValueGetAndDeleter = core.SecondaryValueGetAndDeleter

// SecondaryValueStorage is the object-valued form of upstream implementation's secondary
// storage contract. Some Redis wrappers parse JSON before returning it, so a
// Go implementation cannot expose that behavior through SecondaryStorage's
// string-returning Get method. Configure this interface through
// Options.SecondaryValueStorage instead. Set still receives the canonical JSON
// string written by upstream implementation.
type SecondaryValueStorage = core.SecondaryValueStorage

type SendVerificationEmailInput = core.SendVerificationEmailInput

type Session = core.Session

// SessionCookieLookupOptions controls the public session-cookie reader.
type SessionCookieLookupOptions = core.SessionCookieLookupOptions

// SessionOptions configures database sessions and their cookies.
type SessionOptions = core.SessionOptions

type SessionResult = core.SessionResult

type SetPasswordInput = core.SetPasswordInput

type SignInEmailInput = core.SignInEmailInput

type SignInEmailResult = core.SignInEmailResult

type SignInSocialInput = core.SignInSocialInput

type SignInSocialResult = core.SignInSocialResult

type SignOutInput = core.SignOutInput

type SignOutResult = core.SignOutResult

type SignUpEmailInput = core.SignUpEmailInput

type SignUpEmailResult = core.SignUpEmailResult

type SocialIDTokenInput = core.SocialIDTokenInput

type StatusMessageResult = core.StatusMessageResult

// StatusResult is the common `{status: boolean}` response returned by Better
// Auth mutation endpoints.
type StatusResult = core.StatusResult

type SuccessMessageResult = core.SuccessMessageResult

// TrustedOriginsResolver contributes request-scoped trusted origins. The
// returned slice is copied and empty entries are ignored.
type TrustedOriginsResolver = core.TrustedOriginsResolver

// TypedAccount is the statically typed form of model.Account.
type TypedAccount[Additional any] = core.TypedAccount[Additional]

// TypedAuth binds a concrete user output type to an Auth runtime. The embedded
// runtime retains the normal HTTP and dispatcher surface, while API returns
// that same output type from every user-bearing endpoint.
type TypedAuth[Output any] = core.TypedAuth[Output]

// TypedContext preserves fields contributed by plugin init hooks. Extension is
// explicit because Go cannot synthesize fields onto AuthContext at compile
// time; Runtime still provides the initialized production context.
type TypedContext[Extension any] = core.TypedContext[Extension]

// TypedDirectAPI is the generic user-result counterpart of DirectAPI.
type TypedDirectAPI[Output any] = core.TypedDirectAPI[Output]

// TypedDirectEndpoint binds a direct API name, method, input encoder, and
// output decoder without passing values through any at the public boundary.
type TypedDirectEndpoint[Input, Output any] = core.TypedDirectEndpoint[Input, Output]

// TypedErrorCodes composes core and plugin-specific code sets.
type TypedErrorCodes[PluginCodes any] = core.TypedErrorCodes[PluginCodes]

// TypedPluginContext2 binds two concrete plugin values to the runtime plugin
// registry. Go has no string-literal indexed return types, so known plugins are
// retrieved by stable typed positions while arbitrary IDs use HasPlugin.
type TypedPluginContext2[First, Second any] = core.TypedPluginContext2[First, Second]

// TypedRequestContext retains body and query as independent type parameters.
// In particular, choosing any for Body cannot widen Query to any, mirroring
// upstream implementation's InferCtx any-poisoning guard.
type TypedRequestContext[Body, Query any] = core.TypedRequestContext[Body, Query]

// TypedSession is the statically typed form of model.Session. Additional can
// contain fields contributed by both session.additionalFields and plugins.
type TypedSession[Additional any] = core.TypedSession[Additional]

// TypedSessionInference is the static session/user pair exposed by Better
// Auth's $Infer.Session contract. The two generic arguments allow plugins to
// contribute user and session fields independently without erasing either
// model's base fields.
type TypedSessionInference[UserAdditional, SessionAdditional any] = core.TypedSessionInference[UserAdditional, SessionAdditional]

// TypedSessionResult is the statically typed user counterpart of SessionResult.
type TypedSessionResult[Output any] = core.TypedSessionResult[Output]

// TypedSignInEmailOverrideAPI explicitly shadows DirectAPI.SignInEmail with a
// bodyless plugin result. Other base methods remain promoted through DirectAPI.
type TypedSignInEmailOverrideAPI[Output any] = core.TypedSignInEmailOverrideAPI[Output]

// TypedSignInEmailResult preserves the SignInEmail result while exposing the
// configured static user type.
type TypedSignInEmailResult[Output any] = core.TypedSignInEmailResult[Output]

// TypedSignUpEmailResult preserves the SignUpEmail result while exposing the
// configured static user type.
type TypedSignUpEmailResult[Output any] = core.TypedSignUpEmailResult[Output]

// TypedUser is the statically typed form of model.User. TypeScript can intersect
// configured additional fields directly into an object type; Go represents
// the same composition through Additional while retaining the exact base user
// field types.
type TypedUser[Additional any] = core.TypedUser[Additional]

// TypedVerification is the statically typed form of model.Verification.
type TypedVerification[Additional any] = core.TypedVerification[Additional]

type UnlinkAccountInput = core.UnlinkAccountInput

type UpdateSessionInput = core.UpdateSessionInput

type UpdateSessionResult = core.UpdateSessionResult

type UpdateUserInput = core.UpdateUserInput

// UpstreamError is an initialization or capability error exposed verbatim
// by upstream implementation. The concrete type preserves the upstream error identity for
// callers that need to distinguish configuration errors from transport errors.
type UpstreamError = core.UpstreamError

type User = core.User

// UserDecoder converts the production model.User into a caller-defined static
// output type. This is the Go analogue of upstream implementation inferring a complete user
// result from its configuration type.
type UserDecoder[Output any] = core.UserDecoder[Output]

// UserFieldsDecoder converts the lossless dynamic additional-field map into a
// caller-defined Go type. model.Value fields preserve absent, null, and present
// values, matching upstream implementation's optional nullable inferred output fields.
type UserFieldsDecoder[Additional any] = core.UserFieldsDecoder[Additional]

type UserOptions = core.UserOptions

type Verification = core.Verification

// VerificationIdentifierHasher implements upstream implementation's custom
// { hash(identifier) } storeIdentifier option.
type VerificationIdentifierHasher = core.VerificationIdentifierHasher

// VerificationIdentifierOverride selects a storage rule for identifiers with
// Prefix. Hash takes precedence over Strategy and represents the upstream
// custom-hasher form.
type VerificationIdentifierOverride = core.VerificationIdentifierOverride

// VerificationIdentifierStorage configures the default identifier storage
// rule and optional ordered prefix overrides. Hash takes precedence over
// Strategy and represents the upstream custom-hasher form.
type VerificationIdentifierStorage = core.VerificationIdentifierStorage

// VerificationIdentifierStrategy is a built-in verification identifier
// storage strategy.
type VerificationIdentifierStrategy = core.VerificationIdentifierStrategy

// VerificationOptions controls persistence of single-use verification data.
// With SecondaryStorage or SecondaryValueStorage configured, values are
// cache-only unless StoreInDatabase is true.
type VerificationOptions = core.VerificationOptions

// VerificationValue is the create/reserve input for a single-use value.
type VerificationValue = core.VerificationValue

type VerifyEmailInput = core.VerifyEmailInput

type VerifyEmailResult = core.VerifyEmailResult

type VerifyPasswordInput = core.VerifyPasswordInput

// Constants exported by the core runtime.
const ErrorAccountNotFound = core.ErrorAccountNotFound

const ErrorAsyncValidationNotSupported = core.ErrorAsyncValidationNotSupported

const ErrorBodyMustBeObject = core.ErrorBodyMustBeObject

const ErrorCallbackURLRequired = core.ErrorCallbackURLRequired

const ErrorChangeEmailDisabled = core.ErrorChangeEmailDisabled

const ErrorCredentialAccountNotFound = core.ErrorCredentialAccountNotFound

const ErrorCrossSiteNavigationLoginBlocked = core.ErrorCrossSiteNavigationLoginBlocked

const ErrorEmailAlreadyVerified = core.ErrorEmailAlreadyVerified

const ErrorEmailCannotBeUpdated = core.ErrorEmailCannotBeUpdated

const ErrorEmailMismatch = core.ErrorEmailMismatch

const ErrorEmailNotVerified = core.ErrorEmailNotVerified

const ErrorFailedToCreateSession = core.ErrorFailedToCreateSession

const ErrorFailedToCreateUser = core.ErrorFailedToCreateUser

const ErrorFailedToCreateVerification = core.ErrorFailedToCreateVerification

const ErrorFailedToGetSession = core.ErrorFailedToGetSession

const ErrorFailedToGetUserInfo = core.ErrorFailedToGetUserInfo

const ErrorFailedToUnlinkLastAccount = core.ErrorFailedToUnlinkLastAccount

const ErrorFailedToUpdateUser = core.ErrorFailedToUpdateUser

const ErrorFieldNotAllowed = core.ErrorFieldNotAllowed

const ErrorIDTokenNotSupported = core.ErrorIDTokenNotSupported

const ErrorInvalidCallbackURL = core.ErrorInvalidCallbackURL

const ErrorInvalidEmail = core.ErrorInvalidEmail

const ErrorInvalidEmailOrPassword = core.ErrorInvalidEmailOrPassword

const ErrorInvalidErrorCallbackURL = core.ErrorInvalidErrorCallbackURL

const ErrorInvalidNewUserCallbackURL = core.ErrorInvalidNewUserCallbackURL

const ErrorInvalidOrigin = core.ErrorInvalidOrigin

const ErrorInvalidPassword = core.ErrorInvalidPassword

const ErrorInvalidRedirectURL = core.ErrorInvalidRedirectURL

const ErrorInvalidToken = core.ErrorInvalidToken

const ErrorInvalidUser = core.ErrorInvalidUser

const ErrorLinkedAccountAlreadyExists = core.ErrorLinkedAccountAlreadyExists

const ErrorMethodNeedsDeferredSession = core.ErrorMethodNeedsDeferredSession

const ErrorMissingField = core.ErrorMissingField

const ErrorMissingOrNullOrigin = core.ErrorMissingOrNullOrigin

const ErrorPasswordAlreadySet = core.ErrorPasswordAlreadySet

const ErrorPasswordTooLong = core.ErrorPasswordTooLong

const ErrorPasswordTooShort = core.ErrorPasswordTooShort

const ErrorProviderNotFound = core.ErrorProviderNotFound

const ErrorSessionExpired = core.ErrorSessionExpired

const ErrorSessionNotFresh = core.ErrorSessionNotFresh

const ErrorSocialAccountAlreadyLinked = core.ErrorSocialAccountAlreadyLinked

const ErrorTokenExpired = core.ErrorTokenExpired

const ErrorUserAlreadyExists = core.ErrorUserAlreadyExists

const ErrorUserAlreadyExistsAnotherEmail = core.ErrorUserAlreadyExistsAnotherEmail

const ErrorUserAlreadyHasPassword = core.ErrorUserAlreadyHasPassword

const ErrorUserEmailNotFound = core.ErrorUserEmailNotFound

const ErrorUserNotFound = core.ErrorUserNotFound

const ErrorValidation = core.ErrorValidation

const ErrorVerificationEmailNotEnabled = core.ErrorVerificationEmailNotEnabled

const PluginSessionAuthoritative = core.PluginSessionAuthoritative

const PluginSessionFresh = core.PluginSessionFresh

const PluginSessionOptional = core.PluginSessionOptional

const PluginSessionRequired = core.PluginSessionRequired

// VerificationIdentifierHashed stores SHA-256 identifiers as unpadded
// base64url, matching upstream implementation's "hashed" strategy.
const VerificationIdentifierHashed = core.VerificationIdentifierHashed

// VerificationIdentifierPlain stores identifiers unchanged.
const VerificationIdentifierPlain = core.VerificationIdentifierPlain

// Variables exported by the core runtime.
// BaseErrorMessages is the exact upstream implementation 1.6.26 base error catalog.
var BaseErrorMessages = core.BaseErrorMessages

// ErrFullMigrationsRequireDatabase is returned when full-mode migrations are
// requested without a raw database connection.
var ErrFullMigrationsRequireDatabase = core.ErrFullMigrationsRequireDatabase

// ErrMinimalDirectDatabaseUnsupported is returned when a raw database
// connection is passed to the minimal runtime instead of a storage adapter.
var ErrMinimalDirectDatabaseUnsupported = core.ErrMinimalDirectDatabaseUnsupported

// ErrMinimalMigrationsUnsupported is returned by the minimal runtime because
// schema migrations require the database-specific full runtime upstream.
var ErrMinimalMigrationsUnsupported = core.ErrMinimalMigrationsUnsupported

// Functions exported by the core runtime.
// BindTypedDirectEndpoint constructs a typed façade over a production direct
// endpoint. Plugin overrides can bind the same name with a completely new
// Input and Output type.
func BindTypedDirectEndpoint[Input, Output any](
	auth *Auth,
	name,
	method string,
	encode func(Input) DirectCallInput,
	decode DirectResultDecoder[Output],
) (TypedDirectEndpoint[Input, Output], error) {
	return core.BindTypedDirectEndpoint[Input, Output](auth, name, method, encode, decode)
}

// BindTypedSignInEmailOverrideAPI binds the canonical signInEmail endpoint
// name while retaining the plugin's replacement return type.
func BindTypedSignInEmailOverrideAPI[Output any](
	auth *Auth,
	decode DirectResultDecoder[Output],
) (TypedSignInEmailOverrideAPI[Output], error) {
	return core.BindTypedSignInEmailOverrideAPI[Output](auth, decode)
}

func ComposePluginAPIs2[First, Second any](first First, second Second) PluginAPIs2[First, Second] {
	return core.ComposePluginAPIs2[First, Second](first, second)
}

// DecodeAccount converts a production model.Account to its static form.
func DecodeAccount[Additional any](
	account model.Account,
	decoder DBFieldsDecoder[Additional],
) (TypedAccount[Additional], error) {
	return core.DecodeAccount[Additional](account, decoder)
}

// DecodeDBField reads an optional database field without collapsing the three
// states represented by upstream implementation output types: absent (undefined), explicit
// null, and present. A present value with the wrong Go type is rejected.
func DecodeDBField[Value any](fields model.Fields, name string) (model.Value[Value], error) {
	return core.DecodeDBField[Value](fields, name)
}

// DecodeDirectJSON decodes the exact response body into Output. It is useful
// for typed plugin endpoint façades and rejects malformed JSON.
func DecodeDirectJSON[Output any](result DirectCallResult) (Output, error) {
	return core.DecodeDirectJSON[Output](result)
}

// DecodeSession converts a production model.Session to its static form.
func DecodeSession[Additional any](
	session model.Session,
	decoder DBFieldsDecoder[Additional],
) (TypedSession[Additional], error) {
	return core.DecodeSession[Additional](session, decoder)
}

// DecodeUser converts a model.User into its statically typed public form.
func DecodeUser[Additional any](
	user model.User,
	decoder UserFieldsDecoder[Additional],
) (TypedUser[Additional], error) {
	return core.DecodeUser[Additional](user, decoder)
}

// DecodeUserField reads one configured user field without collapsing absent,
// null, and present values. A present value of the wrong Go type is rejected
// instead of being silently replaced by its zero value.
func DecodeUserField[Value any](fields model.Fields, name string) (model.Value[Value], error) {
	return core.DecodeUserField[Value](fields, name)
}

// DecodeVerification converts a production model.Verification to its static form.
func DecodeVerification[Additional any](
	verification model.Verification,
	decoder DBFieldsDecoder[Additional],
) (TypedVerification[Additional], error) {
	return core.DecodeVerification[Additional](verification, decoder)
}

// ErrorMessage returns a stable message or an empty string for unknown codes.
func ErrorMessage(code ErrorCode) string {
	return core.ErrorMessage(code)
}

// ExpireCookie removes pending writes for a cookie and its chunk variants,
// then appends an expiring cookie while preserving all configured attributes.
func ExpireCookie(ctx *engine.Context, cookieName string, options cookies.Options) {
	core.ExpireCookie(ctx, cookieName, options)
}

// GetCookieCache verifies and decodes a upstream implementation session-data Cookie
// header. A missing cookie is not an error. A present cookie requires a secret,
// matching the upstream helper's fail-closed behavior.
func GetCookieCache(cookieHeader string, options ...CookieCacheLookupOptions) (map[string]any, error) {
	return core.GetCookieCache(cookieHeader, options...)
}

// GetCookieCacheFromHTTPRequest is the net/http form of GetCookieCache.
func GetCookieCacheFromHTTPRequest(request *http.Request, options ...CookieCacheLookupOptions) (map[string]any, error) {
	return core.GetCookieCacheFromHTTPRequest(request, options...)
}

// GetSessionCookie reads a upstream implementation session token from a Cookie header.
func GetSessionCookie(cookieHeader string, options ...SessionCookieLookupOptions) (string, bool) {
	return core.GetSessionCookie(cookieHeader, options...)
}

// GetSessionCookieFromHTTPRequest is the net/http form of GetSessionCookie.
func GetSessionCookieFromHTTPRequest(request *http.Request, options ...SessionCookieLookupOptions) (string, bool) {
	return core.GetSessionCookieFromHTTPRequest(request, options...)
}

// GetSessionCookieFromHeaderGetter reads from any net/http-compatible header
// getter, including inherited and cross-runtime wrappers.
func GetSessionCookieFromHeaderGetter(headers CookieHeaderGetter, options ...SessionCookieLookupOptions) (string, bool) {
	return core.GetSessionCookieFromHeaderGetter(headers, options...)
}

// MustNew constructs an Auth or panics. It is intended for static application
// setup where configuration errors cannot be recovered.
func MustNew(options Options) *Auth {
	return core.MustNew(options)
}

// New validates options, snapshots configuration, and constructs the shared
// dispatcher used by every transport and the direct API.
func New(options Options) (*Auth, error) {
	return core.New(options)
}

// NewMinimal constructs upstream implementation's adapter-only minimal runtime.
func NewMinimal(options Options) (*MinimalAuth, error) {
	return core.NewMinimal(options)
}

// NewMinimalWithDatabase accepts the dynamic database shape exposed by the
// JavaScript initializer. Go storage.Adapter values are supported; raw
// connections are rejected with upstream implementation's exact minimal-mode diagnostic.
func NewMinimalWithDatabase(options Options, database any) (*MinimalAuth, error) {
	return core.NewMinimalWithDatabase(options, database)
}

// NewTypedAuth adds a compile-time user result type to an existing Auth.
func NewTypedAuth[Output any](
	auth *Auth,
	decoder UserDecoder[Output],
) (*TypedAuth[Output], error) {
	return core.NewTypedAuth[Output](auth, decoder)
}

// NewTypedContext binds a caller-defined init extension to an Auth context.
func NewTypedContext[Extension any](auth *Auth, extension Extension) (TypedContext[Extension], error) {
	return core.NewTypedContext[Extension](auth, extension)
}

func NewTypedErrorCodes[PluginCodes any](plugin PluginCodes) TypedErrorCodes[PluginCodes] {
	return core.NewTypedErrorCodes[PluginCodes](plugin)
}

// NewTypedPluginContext2 creates a typed view over two configured plugins.
func NewTypedPluginContext2[First, Second any](
	auth *Auth,
	firstID string,
	first First,
	secondID string,
	second Second,
) (TypedPluginContext2[First, Second], error) {
	return core.NewTypedPluginContext2[First, Second](auth, firstID, first, secondID, second)
}

// NewTypedUserAuth is a convenience binding for TypedUser plus an additional-
// fields decoder. NewTypedAuth can instead bind a completely flat caller type.
func NewTypedUserAuth[Additional any](
	auth *Auth,
	decoder UserFieldsDecoder[Additional],
) (*TypedAuth[TypedUser[Additional]], error) {
	return core.NewTypedUserAuth[Additional](auth, decoder)
}

// NewWithSQLiteDatabase initializes the full runtime from a raw database/sql
// SQLite handle and exposes the native SQLite adapter.
func NewWithSQLiteDatabase(options Options, database *sql.DB) (*Auth, error) {
	return core.NewWithSQLiteDatabase(options, database)
}

// PreserveErrorCodesWithUntypedPlugins is the error-code counterpart of
// PreserveInferenceWithUntypedPlugins.
func PreserveErrorCodesWithUntypedPlugins[PluginCodes any](
	codes TypedErrorCodes[PluginCodes], arg0 ...any,
) TypedErrorCodes[PluginCodes] {
	return core.PreserveErrorCodesWithUntypedPlugins[PluginCodes](codes, arg0...)
}

// PreserveInferenceWithUntypedPlugins deliberately keeps the inferred static
// session type when an integration also supplies dynamically typed plugins.
func PreserveInferenceWithUntypedPlugins[Inference any](
	inference Inference, arg0 ...any,
) Inference {
	return core.PreserveInferenceWithUntypedPlugins[Inference](inference, arg0...)
}

// QueueAfterTransactionHook queues hook on the current adapter scope. Outside
// a scope it executes immediately.
func QueueAfterTransactionHook(ctx context.Context, hook func() error) error {
	return core.QueueAfterTransactionHook(ctx, hook)
}

// RequestContextFromEndpoint returns an independent snapshot of the auth
// context associated with an engine endpoint invocation.
func RequestContextFromEndpoint(ctx *engine.Context) (RequestAuthContext, bool) {
	return core.RequestContextFromEndpoint(ctx)
}

// RequireDBField reads a required configured or plugin database field. Missing,
// null, and wrong-typed values are errors rather than implicit zero values.
func RequireDBField[Value any](fields model.Fields, name string) (Value, error) {
	return core.RequireDBField[Value](fields, name)
}

// RequiredKeysOf returns a compile-time marker without reflection. Result is
// inferred from the shape's method signature on current Go toolchains.
func RequiredKeysOf[
	Result RequiredKeysResult,
	Shape interface{ RequiredKeysResult() Result },
](shape Shape) Result {
	return core.RequiredKeysOf[Result, Shape](shape)
}

// SessionFromEndpointContext returns the logical session/user pair established
// by SessionMiddleware. Returned records are independent copies.
func SessionFromEndpointContext(ctx *engine.Context) (*PluginSessionState, bool) {
	return core.SessionFromEndpointContext(ctx)
}

// SessionMiddleware is the endpoint-local equivalent of upstream implementation's
// sessionMiddleware. It resolves a valid logical session and merges the
// session/user pair into request-local endpoint context for later middleware
// and the handler.
func SessionMiddleware(ctx *engine.Context) (engine.EndpointMiddlewareResult, error) {
	return core.SessionMiddleware(ctx)
}

// SetEndpointSession installs a logical session/user pair for the remainder of
// the current dispatch. Authentication plugins use it when a non-cookie
// credential has already been validated by a before hook.
func SetEndpointSession(ctx *engine.Context, state *PluginSessionState) {
	core.SetEndpointSession(ctx, state)
}
