package providers

func fixturePointer[T any](value T) *T { return &value }

var appleCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{Suite: "apple.createAuthorizationURL", Title: "omits PKCE parameters when no code verifier is provided", Operation: "createAuthorizationURL", Input: struct {
	State        string            "json:\"state\""
	RedirectURI  string            "json:\"redirectURI\""
	CodeVerifier string            "json:\"codeVerifier\""
	TokenNonce   string            "json:\"tokenNonce\""
	RequestNonce string            "json:\"requestNonce\""
	Token        string            "json:\"token\""
	Nonce        string            "json:\"nonce\""
	Headers      map[string]string "json:\"headers\""
}{State: "state", RedirectURI: "https://example.com/api/auth/callback/apple"}, Observation: struct {
	URL                 string   "json:\"url\""
	CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
	CodeChallenge       *string  "json:\"codeChallenge\""
	HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
	Verified            bool     "json:\"verified\""
	FetchURLs           []string "json:\"fetchURLs\""
	SeenPlatform        string   "json:\"seenPlatform\""
}{URL: "https://appleid.apple.com/auth/authorize?response_type=code+id_token&client_id=service.example.app&state=state&scope=email+name&redirect_uri=https%3A%2F%2Fexample.com%2Fapi%2Fauth%2Fcallback%2Fapple&response_mode=form_post"}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{Suite: "apple.createAuthorizationURL", Title: "sends a PKCE code challenge when a code verifier is provided", Operation: "createAuthorizationURL", Input: struct {
	State        string            "json:\"state\""
	RedirectURI  string            "json:\"redirectURI\""
	CodeVerifier string            "json:\"codeVerifier\""
	TokenNonce   string            "json:\"tokenNonce\""
	RequestNonce string            "json:\"requestNonce\""
	Token        string            "json:\"token\""
	Nonce        string            "json:\"nonce\""
	Headers      map[string]string "json:\"headers\""
}{State: "state", RedirectURI: "https://example.com/api/auth/callback/apple", CodeVerifier: "apple-code-verifier"}, Observation: struct {
	URL                 string   "json:\"url\""
	CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
	CodeChallenge       *string  "json:\"codeChallenge\""
	HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
	Verified            bool     "json:\"verified\""
	FetchURLs           []string "json:\"fetchURLs\""
	SeenPlatform        string   "json:\"seenPlatform\""
}{URL: "https://appleid.apple.com/auth/authorize?response_type=code+id_token&client_id=service.example.app&state=state&scope=email+name&redirect_uri=https%3A%2F%2Fexample.com%2Fapi%2Fauth%2Fcallback%2Fapple&response_mode=form_post&code_challenge_method=S256&code_challenge=dopAWBuTN7d3DvrUt5YWt-IOq3Ci_dDqB0V0l9W36fk", CodeChallengeMethod: fixturePointer("S256"), CodeChallenge: fixturePointer("dopAWBuTN7d3DvrUt5YWt-IOq3Ci_dDqB0V0l9W36fk")}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{Suite: "apple.verifyIdToken", Title: "accepts a hashed token nonce when the request provides the raw native iOS nonce", Operation: "verifyIdToken", Input: struct {
	State        string            "json:\"state\""
	RedirectURI  string            "json:\"redirectURI\""
	CodeVerifier string            "json:\"codeVerifier\""
	TokenNonce   string            "json:\"tokenNonce\""
	RequestNonce string            "json:\"requestNonce\""
	Token        string            "json:\"token\""
	Nonce        string            "json:\"nonce\""
	Headers      map[string]string "json:\"headers\""
}{TokenNonce: "87308d3b5d7892b73352f36c8740c993423b20668c47c46e99fa7a84397b8ec8", RequestNonce: "raw-native-ios-nonce"}, Observation: struct {
	URL                 string   "json:\"url\""
	CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
	CodeChallenge       *string  "json:\"codeChallenge\""
	HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
	Verified            bool     "json:\"verified\""
	FetchURLs           []string "json:\"fetchURLs\""
	SeenPlatform        string   "json:\"seenPlatform\""
}{Verified: true, FetchURLs: []string{"https://appleid.apple.com/auth/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{Suite: "apple.verifyIdToken", Title: "accepts a matching raw nonce", Operation: "verifyIdToken", Input: struct {
	State        string            "json:\"state\""
	RedirectURI  string            "json:\"redirectURI\""
	CodeVerifier string            "json:\"codeVerifier\""
	TokenNonce   string            "json:\"tokenNonce\""
	RequestNonce string            "json:\"requestNonce\""
	Token        string            "json:\"token\""
	Nonce        string            "json:\"nonce\""
	Headers      map[string]string "json:\"headers\""
}{TokenNonce: "raw-nonce", RequestNonce: "raw-nonce"}, Observation: struct {
	URL                 string   "json:\"url\""
	CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
	CodeChallenge       *string  "json:\"codeChallenge\""
	HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
	Verified            bool     "json:\"verified\""
	FetchURLs           []string "json:\"fetchURLs\""
	SeenPlatform        string   "json:\"seenPlatform\""
}{Verified: true, FetchURLs: []string{"https://appleid.apple.com/auth/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{Suite: "apple.verifyIdToken", Title: "forwards request ctx to a custom verifyIdToken option", Operation: "customVerifyIdToken", Input: struct {
	State        string            "json:\"state\""
	RedirectURI  string            "json:\"redirectURI\""
	CodeVerifier string            "json:\"codeVerifier\""
	TokenNonce   string            "json:\"tokenNonce\""
	RequestNonce string            "json:\"requestNonce\""
	Token        string            "json:\"token\""
	Nonce        string            "json:\"nonce\""
	Headers      map[string]string "json:\"headers\""
}{Token: "token", Nonce: "nonce", Headers: map[string]string{"x-platform": "ios"}}, Observation: struct {
	URL                 string   "json:\"url\""
	CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
	CodeChallenge       *string  "json:\"codeChallenge\""
	HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
	Verified            bool     "json:\"verified\""
	FetchURLs           []string "json:\"fetchURLs\""
	SeenPlatform        string   "json:\"seenPlatform\""
}{Verified: true, SeenPlatform: "ios"}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		State        string            "json:\"state\""
		RedirectURI  string            "json:\"redirectURI\""
		CodeVerifier string            "json:\"codeVerifier\""
		TokenNonce   string            "json:\"tokenNonce\""
		RequestNonce string            "json:\"requestNonce\""
		Token        string            "json:\"token\""
		Nonce        string            "json:\"nonce\""
		Headers      map[string]string "json:\"headers\""
	} "json:\"input\""
	Observation struct {
		URL                 string   "json:\"url\""
		CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
		CodeChallenge       *string  "json:\"codeChallenge\""
		HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
		Verified            bool     "json:\"verified\""
		FetchURLs           []string "json:\"fetchURLs\""
		SeenPlatform        string   "json:\"seenPlatform\""
	} "json:\"observation\""
}{Suite: "apple.verifyIdToken", Title: "rejects a mismatched nonce", Operation: "verifyIdToken", Input: struct {
	State        string            "json:\"state\""
	RedirectURI  string            "json:\"redirectURI\""
	CodeVerifier string            "json:\"codeVerifier\""
	TokenNonce   string            "json:\"tokenNonce\""
	RequestNonce string            "json:\"requestNonce\""
	Token        string            "json:\"token\""
	Nonce        string            "json:\"nonce\""
	Headers      map[string]string "json:\"headers\""
}{TokenNonce: "87308d3b5d7892b73352f36c8740c993423b20668c47c46e99fa7a84397b8ec8", RequestNonce: "different-nonce"}, Observation: struct {
	URL                 string   "json:\"url\""
	CodeChallengeMethod *string  "json:\"codeChallengeMethod\""
	CodeChallenge       *string  "json:\"codeChallenge\""
	HasCodeVerifier     bool     "json:\"hasCodeVerifier\""
	Verified            bool     "json:\"verified\""
	FetchURLs           []string "json:\"fetchURLs\""
	SeenPlatform        string   "json:\"seenPlatform\""
}{FetchURLs: []string{"https://appleid.apple.com/auth/keys"}}}}

var facebookCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.getUserInfo (opaque access token)", Title: "rejects a token issued to a different app (token substitution)", Operation: "getUserInfo", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret", Token: "foreign-app-token", Debug: map[string]interface{}{"app_id": "someone-elses-app", "is_valid": true, "user_id": "other-user"}, Profile: map[string]interface{}{"email": "other-user@example.com", "id": "other-user", "name": "User other-user", "picture": map[string]interface{}{"data": map[string]interface{}{"height": 100, "is_silhouette": false, "url": "https://x", "width": 100}}}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(true), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=foreign-app-token&access_token=fb-app%7Cfb-secret", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.getUserInfo (opaque access token)", Title: "rejects when no access token is supplied", Operation: "getUserInfo", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret"}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(true), Requests: []facebookRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.getUserInfo (opaque access token)", Title: "rejects when the profile id does not match the validated token", Operation: "getUserInfo", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret", Token: "opaque-access-token", Debug: map[string]interface{}{"app_id": "fb-app", "is_valid": true, "user_id": "u1"}, Profile: map[string]interface{}{"email": "a-different-user@example.com", "id": "a-different-user", "name": "User a-different-user", "picture": map[string]interface{}{"data": map[string]interface{}{"height": 100, "is_silhouette": false, "url": "https://x", "width": 100}}}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(true), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=opaque-access-token&access_token=fb-app%7Cfb-secret", Method: "GET"}, facebookRequestObservation{URL: "https://graph.facebook.com/me?fields=id%2Cname%2Cemail%2Cpicture", Method: "GET", Authorization: fixturePointer("Bearer opaque-access-token")}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.getUserInfo (opaque access token)", Title: "returns the profile for a token bound to the configured app", Operation: "getUserInfo", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret", Token: "opaque-access-token", Debug: map[string]interface{}{"app_id": "fb-app", "is_valid": true, "user_id": "u1"}, Profile: map[string]interface{}{"email": "u1@example.com", "id": "u1", "name": "User u1", "picture": map[string]interface{}{"data": map[string]interface{}{"height": 100, "is_silhouette": false, "url": "https://x", "width": 100}}}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(false), UserID: fixturePointer("u1"), UserEmail: fixturePointer("u1@example.com"), UserImage: fixturePointer("https://x"), EmailVerified: fixturePointer(false), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=opaque-access-token&access_token=fb-app%7Cfb-secret", Method: "GET"}, facebookRequestObservation{URL: "https://graph.facebook.com/me?fields=id%2Cname%2Cemail%2Cpicture", Method: "GET", Authorization: fixturePointer("Bearer opaque-access-token")}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.verifyIdToken (opaque access token)", Title: "accepts a token bound to any configured client id", Operation: "verifyIdToken", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: []interface{}{"fb-app", "fb-mobile"}, ClientSecret: "fb-secret", Token: "opaque-access-token", Debug: map[string]interface{}{"app_id": "fb-mobile", "is_valid": true, "user_id": "u1"}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{Verified: fixturePointer(true), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=opaque-access-token&access_token=fb-app%7Cfb-secret", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.verifyIdToken (opaque access token)", Title: "accepts an opaque token bound to the configured app", Operation: "verifyIdToken", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret", Token: "opaque-access-token", Debug: map[string]interface{}{"app_id": "fb-app", "is_valid": true, "user_id": "u1"}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{Verified: fixturePointer(true), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=opaque-access-token&access_token=fb-app%7Cfb-secret", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.verifyIdToken (opaque access token)", Title: "rejects an invalid opaque token", Operation: "verifyIdToken", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret", Token: "revoked-token", Debug: map[string]interface{}{"app_id": "fb-app", "is_valid": false, "user_id": "u1"}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{Verified: fixturePointer(false), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=revoked-token&access_token=fb-app%7Cfb-secret", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.verifyIdToken (opaque access token)", Title: "rejects an opaque token issued to a different app", Operation: "verifyIdToken", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", ClientSecret: "fb-secret", Token: "foreign-app-token", Debug: map[string]interface{}{"app_id": "someone-elses-app", "is_valid": true, "user_id": "u1"}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{Verified: fixturePointer(false), Requests: []facebookRequestObservation{facebookRequestObservation{URL: "https://graph.facebook.com/debug_token?input_token=foreign-app-token&access_token=fb-app%7Cfb-secret", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     interface{}            "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		Token        string                 "json:\"token\""
		Debug        map[string]interface{} "json:\"debug\""
		Profile      map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		Verified      *bool                        "json:\"verified\""
		ResultNull    *bool                        "json:\"resultNull\""
		UserID        *string                      "json:\"userId\""
		UserEmail     *string                      "json:\"userEmail\""
		UserImage     *string                      "json:\"userImage\""
		EmailVerified *bool                        "json:\"emailVerified\""
		Requests      []facebookRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "facebook.verifyIdToken (opaque access token)", Title: "rejects when no client secret is configured", Operation: "verifyIdToken", Input: struct {
	ClientID     interface{}            "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	Token        string                 "json:\"token\""
	Debug        map[string]interface{} "json:\"debug\""
	Profile      map[string]interface{} "json:\"profile\""
}{ClientID: "fb-app", Token: "opaque-access-token", Debug: map[string]interface{}{"app_id": "fb-app", "is_valid": true, "user_id": "u1"}}, Observation: struct {
	Verified      *bool                        "json:\"verified\""
	ResultNull    *bool                        "json:\"resultNull\""
	UserID        *string                      "json:\"userId\""
	UserEmail     *string                      "json:\"userEmail\""
	UserImage     *string                      "json:\"userImage\""
	EmailVerified *bool                        "json:\"emailVerified\""
	Requests      []facebookRequestObservation "json:\"requests\""
}{Verified: fixturePointer(false), Requests: []facebookRequestObservation{}}}}

var googleCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > getUserInfo", Title: "returns null when the hd claim does not match", Operation: "getUserInfo", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("example.com"), TokenHD: fixturePointer("other.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(true), Requests: []googleRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > getUserInfo", Title: "returns null when the hd claim is missing and hd is configured", Operation: "getUserInfo", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("example.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(true), Requests: []googleRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > getUserInfo", Title: "returns null when the hd claim is missing and hd is configured as a wildcard", Operation: "getUserInfo", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("*")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(true), Requests: []googleRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > getUserInfo", Title: "returns the user for any Workspace hd when hd is configured as a wildcard", Operation: "getUserInfo", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("*"), TokenHD: fixturePointer("example.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(false), UserEmail: fixturePointer("user@example.com"), Requests: []googleRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > getUserInfo", Title: "returns the user regardless of hd when hd is not configured", Operation: "getUserInfo", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{TokenHD: fixturePointer("anything.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(false), UserEmail: fixturePointer("user@example.com"), Requests: []googleRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > getUserInfo", Title: "returns the user when the hd claim matches", Operation: "getUserInfo", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("example.com"), TokenHD: fixturePointer("example.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{ResultNull: fixturePointer(false), UserEmail: fixturePointer("user@example.com"), Requests: []googleRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > verifyIdToken", Title: "accepts a token whose hd claim matches the configured hd", Operation: "verifyIdToken", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("example.com"), TokenHD: fixturePointer("example.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{Verified: fixturePointer(true), Requests: []googleRequestObservation{googleRequestObservation{URL: "https://www.googleapis.com/oauth2/v3/certs", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > verifyIdToken", Title: "accepts any Workspace hd when hd is configured as a wildcard", Operation: "verifyIdToken", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("*"), TokenHD: fixturePointer("example.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{Verified: fixturePointer(true), Requests: []googleRequestObservation{googleRequestObservation{URL: "https://www.googleapis.com/oauth2/v3/certs", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > verifyIdToken", Title: "does not require an hd claim when hd is not configured", Operation: "verifyIdToken", Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{Verified: fixturePointer(true), Requests: []googleRequestObservation{googleRequestObservation{URL: "https://www.googleapis.com/oauth2/v3/certs", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > verifyIdToken", Title: "rejects a token missing the hd claim when hd is configured", Operation: "verifyIdToken", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("example.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{Verified: fixturePointer(false), Requests: []googleRequestObservation{googleRequestObservation{URL: "https://www.googleapis.com/oauth2/v3/certs", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > verifyIdToken", Title: "rejects a token missing the hd claim when hd is configured as a wildcard", Operation: "verifyIdToken", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("*")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{Verified: fixturePointer(false), Requests: []googleRequestObservation{googleRequestObservation{URL: "https://www.googleapis.com/oauth2/v3/certs", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ConfiguredHD *string "json:\"configuredHD\""
		TokenHD      *string "json:\"tokenHD\""
	} "json:\"input\""
	Observation struct {
		Verified   *bool                      "json:\"verified\""
		ResultNull *bool                      "json:\"resultNull\""
		UserEmail  *string                    "json:\"userEmail\""
		Requests   []googleRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "google hosted domain (hd) enforcement > verifyIdToken", Title: "rejects a token whose hd claim does not match", Operation: "verifyIdToken", Input: struct {
	ConfiguredHD *string "json:\"configuredHD\""
	TokenHD      *string "json:\"tokenHD\""
}{ConfiguredHD: fixturePointer("example.com"), TokenHD: fixturePointer("other.com")}, Observation: struct {
	Verified   *bool                      "json:\"verified\""
	ResultNull *bool                      "json:\"resultNull\""
	UserEmail  *string                    "json:\"userEmail\""
	Requests   []googleRequestObservation "json:\"requests\""
}{Verified: fixturePointer(false), Requests: []googleRequestObservation{googleRequestObservation{URL: "https://www.googleapis.com/oauth2/v3/certs", Method: "GET"}}}}}

var microsoftEntraIDCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "accepts a consumer-tenant token under consumers", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "consumers", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("9188040d-6c67-4c5b-b112-36a304b66dad"), Issuer: "https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{true}, FetchURLs: []string{"https://login.microsoftonline.com/consumers/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "accepts a valid token when the authority is configured with a trailing slash", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "common", Authority: fixturePointer("https://login.microsoftonline.com/"), Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("11111111-2222-3333-4444-555555555555"), Issuer: "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{true}, FetchURLs: []string{"https://login.microsoftonline.com/common/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "accepts a work-tenant token under organizations", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "organizations", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("11111111-2222-3333-4444-555555555555"), Issuer: "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{true}, FetchURLs: []string{"https://login.microsoftonline.com/organizations/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "accepts any tenant under common", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "common", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("11111111-2222-3333-4444-555555555555"), Issuer: "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555/v2.0"}, struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("9188040d-6c67-4c5b-b112-36a304b66dad"), Issuer: "https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{true, true}, FetchURLs: []string{"https://login.microsoftonline.com/common/discovery/v2.0/keys", "https://login.microsoftonline.com/common/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "rejects a consumer-tenant token when restricted to organizations", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "organizations", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("9188040d-6c67-4c5b-b112-36a304b66dad"), Issuer: "https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{false}, FetchURLs: []string{"https://login.microsoftonline.com/organizations/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "rejects a token whose issuer does not name its own tenant", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "common", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("11111111-2222-3333-4444-555555555555"), Issuer: "https://login.microsoftonline.com/9188040d-6c67-4c5b-b112-36a304b66dad/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{false}, FetchURLs: []string{"https://login.microsoftonline.com/common/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "rejects a token with a non-string tid", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "common", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{Issuer: "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{false}, FetchURLs: []string{"https://login.microsoftonline.com/common/discovery/v2.0/keys"}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		TenantID  string  "json:\"tenantId\""
		Authority *string "json:\"authority\""
		Tokens    []struct {
			TID    *string "json:\"tid\""
			Issuer string  "json:\"issuer\""
		} "json:\"tokens\""
	} "json:\"input\""
	Observation struct {
		Verified  []bool   "json:\"verified\""
		FetchURLs []string "json:\"fetchURLs\""
	} "json:\"observation\""
}{Suite: "microsoft.verifyIdToken tenant enforcement", Title: "rejects a work-tenant token when restricted to consumers", Operation: "verifyIdToken", Input: struct {
	TenantID  string  "json:\"tenantId\""
	Authority *string "json:\"authority\""
	Tokens    []struct {
		TID    *string "json:\"tid\""
		Issuer string  "json:\"issuer\""
	} "json:\"tokens\""
}{TenantID: "consumers", Tokens: []struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{struct {
	TID    *string "json:\"tid\""
	Issuer string  "json:\"issuer\""
}{TID: fixturePointer("11111111-2222-3333-4444-555555555555"), Issuer: "https://login.microsoftonline.com/11111111-2222-3333-4444-555555555555/v2.0"}}}, Observation: struct {
	Verified  []bool   "json:\"verified\""
	FetchURLs []string "json:\"fetchURLs\""
}{Verified: []bool{false}, FetchURLs: []string{"https://login.microsoftonline.com/consumers/discovery/v2.0/keys"}}}}

var paypalCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID       string                 "json:\"clientId\""
		ClientSecret   string                 "json:\"clientSecret\""
		Environment    string                 "json:\"environment\""
		AccessToken    string                 "json:\"accessToken\""
		IDTokenSubject string                 "json:\"idTokenSubject\""
		Profile        map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool                       "json:\"resultNull\""
		User       *paypalUserObservation     "json:\"user\""
		Data       map[string]interface{}     "json:\"data\""
		Requests   []paypalRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID       string                 "json:\"clientId\""
		ClientSecret   string                 "json:\"clientSecret\""
		Environment    string                 "json:\"environment\""
		AccessToken    string                 "json:\"accessToken\""
		IDTokenSubject string                 "json:\"idTokenSubject\""
		Profile        map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool                       "json:\"resultNull\""
		User       *paypalUserObservation     "json:\"user\""
		Data       map[string]interface{}     "json:\"data\""
		Requests   []paypalRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "paypal.getUserInfo", Title: "keeps the PayPal user id when the profile subject matches", Operation: "getUserInfo", Input: struct {
	ClientID       string                 "json:\"clientId\""
	ClientSecret   string                 "json:\"clientSecret\""
	Environment    string                 "json:\"environment\""
	AccessToken    string                 "json:\"accessToken\""
	IDTokenSubject string                 "json:\"idTokenSubject\""
	Profile        map[string]interface{} "json:\"profile\""
}{ClientID: "paypal-client-id", ClientSecret: "paypal-client-secret", Environment: "live", AccessToken: "paypal-access-token", IDTokenSubject: "paypal-subject-123", Profile: map[string]interface{}{"email": "paypal-user@example.com", "email_verified": true, "family_name": "User", "given_name": "PayPal", "name": "PayPal User", "picture": "https://example.com/avatar.png", "sub": "paypal-subject-123", "user_id": "paypal-user-123"}}, Observation: struct {
	ResultNull bool                       "json:\"resultNull\""
	User       *paypalUserObservation     "json:\"user\""
	Data       map[string]interface{}     "json:\"data\""
	Requests   []paypalRequestObservation "json:\"requests\""
}{User: fixturePointer(paypalUserObservation{ID: "paypal-user-123", Name: "PayPal User", Email: fixturePointer("paypal-user@example.com"), Image: "https://example.com/avatar.png", EmailVerified: true}), Data: map[string]interface{}{"email": "paypal-user@example.com", "email_verified": true, "family_name": "User", "given_name": "PayPal", "name": "PayPal User", "picture": "https://example.com/avatar.png", "sub": "paypal-subject-123", "user_id": "paypal-user-123"}, Requests: []paypalRequestObservation{paypalRequestObservation{URL: "https://api-m.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1", Method: "GET", Authorization: fixturePointer("Bearer paypal-access-token"), Accept: fixturePointer("application/json")}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID       string                 "json:\"clientId\""
		ClientSecret   string                 "json:\"clientSecret\""
		Environment    string                 "json:\"environment\""
		AccessToken    string                 "json:\"accessToken\""
		IDTokenSubject string                 "json:\"idTokenSubject\""
		Profile        map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool                       "json:\"resultNull\""
		User       *paypalUserObservation     "json:\"user\""
		Data       map[string]interface{}     "json:\"data\""
		Requests   []paypalRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "paypal.getUserInfo", Title: "prefers the profile subject over user_id when validating the id token", Operation: "getUserInfo", Input: struct {
	ClientID       string                 "json:\"clientId\""
	ClientSecret   string                 "json:\"clientSecret\""
	Environment    string                 "json:\"environment\""
	AccessToken    string                 "json:\"accessToken\""
	IDTokenSubject string                 "json:\"idTokenSubject\""
	Profile        map[string]interface{} "json:\"profile\""
}{ClientID: "paypal-client-id", ClientSecret: "paypal-client-secret", Environment: "live", AccessToken: "paypal-access-token", IDTokenSubject: "paypal-user-123", Profile: map[string]interface{}{"email": "paypal-user@example.com", "email_verified": true, "family_name": "User", "given_name": "PayPal", "name": "PayPal User", "picture": "https://example.com/avatar.png", "sub": "paypal-user-456", "user_id": "paypal-user-123"}}, Observation: struct {
	ResultNull bool                       "json:\"resultNull\""
	User       *paypalUserObservation     "json:\"user\""
	Data       map[string]interface{}     "json:\"data\""
	Requests   []paypalRequestObservation "json:\"requests\""
}{ResultNull: true, Requests: []paypalRequestObservation{paypalRequestObservation{URL: "https://api-m.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1", Method: "GET", Authorization: fixturePointer("Bearer paypal-access-token"), Accept: fixturePointer("application/json")}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID       string                 "json:\"clientId\""
		ClientSecret   string                 "json:\"clientSecret\""
		Environment    string                 "json:\"environment\""
		AccessToken    string                 "json:\"accessToken\""
		IDTokenSubject string                 "json:\"idTokenSubject\""
		Profile        map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool                       "json:\"resultNull\""
		User       *paypalUserObservation     "json:\"user\""
		Data       map[string]interface{}     "json:\"data\""
		Requests   []paypalRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "paypal.getUserInfo", Title: "returns null when the id token subject does not match the profile", Operation: "getUserInfo", Input: struct {
	ClientID       string                 "json:\"clientId\""
	ClientSecret   string                 "json:\"clientSecret\""
	Environment    string                 "json:\"environment\""
	AccessToken    string                 "json:\"accessToken\""
	IDTokenSubject string                 "json:\"idTokenSubject\""
	Profile        map[string]interface{} "json:\"profile\""
}{ClientID: "paypal-client-id", ClientSecret: "paypal-client-secret", Environment: "live", AccessToken: "paypal-access-token", IDTokenSubject: "paypal-user-456", Profile: map[string]interface{}{"email": "paypal-user@example.com", "email_verified": true, "family_name": "User", "given_name": "PayPal", "name": "PayPal User", "picture": "https://example.com/avatar.png", "user_id": "paypal-user-123"}}, Observation: struct {
	ResultNull bool                       "json:\"resultNull\""
	User       *paypalUserObservation     "json:\"user\""
	Data       map[string]interface{}     "json:\"data\""
	Requests   []paypalRequestObservation "json:\"requests\""
}{ResultNull: true, Requests: []paypalRequestObservation{paypalRequestObservation{URL: "https://api-m.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1", Method: "GET", Authorization: fixturePointer("Bearer paypal-access-token"), Accept: fixturePointer("application/json")}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID       string                 "json:\"clientId\""
		ClientSecret   string                 "json:\"clientSecret\""
		Environment    string                 "json:\"environment\""
		AccessToken    string                 "json:\"accessToken\""
		IDTokenSubject string                 "json:\"idTokenSubject\""
		Profile        map[string]interface{} "json:\"profile\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool                       "json:\"resultNull\""
		User       *paypalUserObservation     "json:\"user\""
		Data       map[string]interface{}     "json:\"data\""
		Requests   []paypalRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "paypal.getUserInfo", Title: "returns user info when the id token subject matches the profile", Operation: "getUserInfo", Input: struct {
	ClientID       string                 "json:\"clientId\""
	ClientSecret   string                 "json:\"clientSecret\""
	Environment    string                 "json:\"environment\""
	AccessToken    string                 "json:\"accessToken\""
	IDTokenSubject string                 "json:\"idTokenSubject\""
	Profile        map[string]interface{} "json:\"profile\""
}{ClientID: "paypal-client-id", ClientSecret: "paypal-client-secret", Environment: "live", AccessToken: "paypal-access-token", IDTokenSubject: "paypal-user-123", Profile: map[string]interface{}{"email": "paypal-user@example.com", "email_verified": true, "family_name": "User", "given_name": "PayPal", "name": "PayPal User", "picture": "https://example.com/avatar.png", "user_id": "paypal-user-123"}}, Observation: struct {
	ResultNull bool                       "json:\"resultNull\""
	User       *paypalUserObservation     "json:\"user\""
	Data       map[string]interface{}     "json:\"data\""
	Requests   []paypalRequestObservation "json:\"requests\""
}{User: fixturePointer(paypalUserObservation{ID: "paypal-user-123", Name: "PayPal User", Email: fixturePointer("paypal-user@example.com"), Image: "https://example.com/avatar.png", EmailVerified: true}), Data: map[string]interface{}{"email": "paypal-user@example.com", "email_verified": true, "family_name": "User", "given_name": "PayPal", "name": "PayPal User", "picture": "https://example.com/avatar.png", "user_id": "paypal-user-123"}, Requests: []paypalRequestObservation{paypalRequestObservation{URL: "https://api-m.paypal.com/v1/identity/oauth2/userinfo?schema=paypalv1.1", Method: "GET", Authorization: fixturePointer("Bearer paypal-access-token"), Accept: fixturePointer("application/json")}}}}}

var redditCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                   "json:\"clientId\""
		ClientSecret string                   "json:\"clientSecret\""
		Profiles     []map[string]interface{} "json:\"profiles\""
		AccessTokens []string                 "json:\"accessTokens\""
		MappedEmail  *string                  "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		Users                      []redditUserObservation    "json:\"users\""
		EmailsDistinct             *bool                      "json:\"emailsDistinct\""
		EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
		Requests                   []redditRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                   "json:\"clientId\""
		ClientSecret string                   "json:\"clientSecret\""
		Profiles     []map[string]interface{} "json:\"profiles\""
		AccessTokens []string                 "json:\"accessTokens\""
		MappedEmail  *string                  "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		Users                      []redditUserObservation    "json:\"users\""
		EmailsDistinct             *bool                      "json:\"emailsDistinct\""
		EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
		Requests                   []redditRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "reddit.getUserInfo (no provider email)", Title: "gives distinct users distinct placeholder emails", Operation: "getUserInfo", Input: struct {
	ClientID     string                   "json:\"clientId\""
	ClientSecret string                   "json:\"clientSecret\""
	Profiles     []map[string]interface{} "json:\"profiles\""
	AccessTokens []string                 "json:\"accessTokens\""
	MappedEmail  *string                  "json:\"mappedEmail\""
}{ClientID: "reddit-app", ClientSecret: "reddit-secret", Profiles: []map[string]interface{}{map[string]interface{}{"has_verified_email": true, "icon_img": nil, "id": "user-a", "name": "a", "oauth_client_id": "same-client", "verified": true}, map[string]interface{}{"has_verified_email": true, "icon_img": nil, "id": "user-b", "name": "b", "oauth_client_id": "same-client", "verified": true}}, AccessTokens: []string{"t-a", "t-b"}}, Observation: struct {
	Users                      []redditUserObservation    "json:\"users\""
	EmailsDistinct             *bool                      "json:\"emailsDistinct\""
	EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
	Requests                   []redditRequestObservation "json:\"requests\""
}{Users: []redditUserObservation{redditUserObservation{ID: fixturePointer("user-a"), Name: fixturePointer("a"), Email: fixturePointer("user-a@reddit.invalid"), EmailVerified: fixturePointer(false)}, redditUserObservation{ID: fixturePointer("user-b"), Name: fixturePointer("b"), Email: fixturePointer("user-b@reddit.invalid"), EmailVerified: fixturePointer(false)}}, EmailsDistinct: fixturePointer(true), Requests: []redditRequestObservation{redditRequestObservation{URL: "https://oauth.reddit.com/api/v1/me", Method: "GET", Authorization: "Bearer t-a", UserAgent: "single-auth"}, redditRequestObservation{URL: "https://oauth.reddit.com/api/v1/me", Method: "GET", Authorization: "Bearer t-b", UserAgent: "single-auth"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                   "json:\"clientId\""
		ClientSecret string                   "json:\"clientSecret\""
		Profiles     []map[string]interface{} "json:\"profiles\""
		AccessTokens []string                 "json:\"accessTokens\""
		MappedEmail  *string                  "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		Users                      []redditUserObservation    "json:\"users\""
		EmailsDistinct             *bool                      "json:\"emailsDistinct\""
		EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
		Requests                   []redditRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "reddit.getUserInfo (no provider email)", Title: "lets mapProfileToUser supply a real email", Operation: "getUserInfo", Input: struct {
	ClientID     string                   "json:\"clientId\""
	ClientSecret string                   "json:\"clientSecret\""
	Profiles     []map[string]interface{} "json:\"profiles\""
	AccessTokens []string                 "json:\"accessTokens\""
	MappedEmail  *string                  "json:\"mappedEmail\""
}{ClientID: "reddit-app", ClientSecret: "reddit-secret", Profiles: []map[string]interface{}{map[string]interface{}{"has_verified_email": true, "icon_img": nil, "id": "reddit-user-2", "name": "mapped", "oauth_client_id": "client", "verified": true}}, AccessTokens: []string{"t"}, MappedEmail: fixturePointer("real@example.com")}, Observation: struct {
	Users                      []redditUserObservation    "json:\"users\""
	EmailsDistinct             *bool                      "json:\"emailsDistinct\""
	EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
	Requests                   []redditRequestObservation "json:\"requests\""
}{Users: []redditUserObservation{redditUserObservation{ID: fixturePointer("reddit-user-2"), Name: fixturePointer("mapped"), Email: fixturePointer("real@example.com"), EmailVerified: fixturePointer(false)}}, Requests: []redditRequestObservation{redditRequestObservation{URL: "https://oauth.reddit.com/api/v1/me", Method: "GET", Authorization: "Bearer t", UserAgent: "single-auth"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                   "json:\"clientId\""
		ClientSecret string                   "json:\"clientSecret\""
		Profiles     []map[string]interface{} "json:\"profiles\""
		AccessTokens []string                 "json:\"accessTokens\""
		MappedEmail  *string                  "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		Users                      []redditUserObservation    "json:\"users\""
		EmailsDistinct             *bool                      "json:\"emailsDistinct\""
		EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
		Requests                   []redditRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "reddit.getUserInfo (no provider email)", Title: "synthesizes a non-routable placeholder email and never trusts oauth_client_id", Operation: "getUserInfo", Input: struct {
	ClientID     string                   "json:\"clientId\""
	ClientSecret string                   "json:\"clientSecret\""
	Profiles     []map[string]interface{} "json:\"profiles\""
	AccessTokens []string                 "json:\"accessTokens\""
	MappedEmail  *string                  "json:\"mappedEmail\""
}{ClientID: "reddit-app", ClientSecret: "reddit-secret", Profiles: []map[string]interface{}{map[string]interface{}{"has_verified_email": true, "icon_img": "https://example.com/avatar.png", "id": "reddit-user-1", "name": "spez", "oauth_client_id": "shared-app-client-id", "verified": true}}, AccessTokens: []string{"access-token"}}, Observation: struct {
	Users                      []redditUserObservation    "json:\"users\""
	EmailsDistinct             *bool                      "json:\"emailsDistinct\""
	EmailsContainOAuthClientID bool                       "json:\"emailsContainOAuthClientId\""
	Requests                   []redditRequestObservation "json:\"requests\""
}{Users: []redditUserObservation{redditUserObservation{ID: fixturePointer("reddit-user-1"), Name: fixturePointer("spez"), Email: fixturePointer("reddit-user-1@reddit.invalid"), EmailVerified: fixturePointer(false), Image: fixturePointer("https://example.com/avatar.png")}}, Requests: []redditRequestObservation{redditRequestObservation{URL: "https://oauth.reddit.com/api/v1/me", Method: "GET", Authorization: "Bearer access-token", UserAgent: "single-auth"}}}}}

var wechatCases = []struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                 "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		AccessToken  string                 "json:\"accessToken\""
		OpenID       *string                "json:\"openid\""
		Profile      map[string]interface{} "json:\"profile\""
		MappedEmail  *string                "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool "json:\"resultNull\""
		wechatUserObservation
		Data     map[string]interface{}     "json:\"data\""
		Requests []wechatRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                 "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		AccessToken  string                 "json:\"accessToken\""
		OpenID       *string                "json:\"openid\""
		Profile      map[string]interface{} "json:\"profile\""
		MappedEmail  *string                "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool "json:\"resultNull\""
		wechatUserObservation
		Data     map[string]interface{}     "json:\"data\""
		Requests []wechatRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "wechat.getUserInfo (no provider email)", Title: "falls back to openid for the placeholder when unionid is absent", Operation: "getUserInfo", Input: struct {
	ClientID     string                 "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	AccessToken  string                 "json:\"accessToken\""
	OpenID       *string                "json:\"openid\""
	Profile      map[string]interface{} "json:\"profile\""
	MappedEmail  *string                "json:\"mappedEmail\""
}{ClientID: "wx-app", ClientSecret: "wx-secret", AccessToken: "access-token", OpenID: fixturePointer("open-456"), Profile: map[string]interface{}{"headimgurl": "https://example.com/avatar.png", "nickname": "No Union", "openid": "open-456"}}, Observation: struct {
	ResultNull bool "json:\"resultNull\""
	wechatUserObservation
	Data     map[string]interface{}     "json:\"data\""
	Requests []wechatRequestObservation "json:\"requests\""
}{wechatUserObservation: wechatUserObservation{ID: fixturePointer("open-456"), Name: fixturePointer("No Union"), Email: fixturePointer("open-456@wechat.invalid"), Image: fixturePointer("https://example.com/avatar.png"), EmailVerified: fixturePointer(false)}, Data: map[string]interface{}{"headimgurl": "https://example.com/avatar.png", "nickname": "No Union", "openid": "open-456"}, Requests: []wechatRequestObservation{wechatRequestObservation{URL: "https://api.weixin.qq.com/sns/userinfo?access_token=access-token&openid=open-456&lang=zh_CN", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                 "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		AccessToken  string                 "json:\"accessToken\""
		OpenID       *string                "json:\"openid\""
		Profile      map[string]interface{} "json:\"profile\""
		MappedEmail  *string                "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool "json:\"resultNull\""
		wechatUserObservation
		Data     map[string]interface{}     "json:\"data\""
		Requests []wechatRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "wechat.getUserInfo (no provider email)", Title: "lets mapProfileToUser supply a real email", Operation: "getUserInfo", Input: struct {
	ClientID     string                 "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	AccessToken  string                 "json:\"accessToken\""
	OpenID       *string                "json:\"openid\""
	Profile      map[string]interface{} "json:\"profile\""
	MappedEmail  *string                "json:\"mappedEmail\""
}{ClientID: "wx-app", ClientSecret: "wx-secret", AccessToken: "access-token", OpenID: fixturePointer("open-789"), Profile: map[string]interface{}{"headimgurl": "https://example.com/avatar.png", "nickname": "Mapped User", "openid": "open-789", "unionid": "union-xyz"}, MappedEmail: fixturePointer("real@example.com")}, Observation: struct {
	ResultNull bool "json:\"resultNull\""
	wechatUserObservation
	Data     map[string]interface{}     "json:\"data\""
	Requests []wechatRequestObservation "json:\"requests\""
}{wechatUserObservation: wechatUserObservation{ID: fixturePointer("union-xyz"), Name: fixturePointer("Mapped User"), Email: fixturePointer("real@example.com"), Image: fixturePointer("https://example.com/avatar.png"), EmailVerified: fixturePointer(false)}, Data: map[string]interface{}{"headimgurl": "https://example.com/avatar.png", "nickname": "Mapped User", "openid": "open-789", "unionid": "union-xyz"}, Requests: []wechatRequestObservation{wechatRequestObservation{URL: "https://api.weixin.qq.com/sns/userinfo?access_token=access-token&openid=open-789&lang=zh_CN", Method: "GET"}}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                 "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		AccessToken  string                 "json:\"accessToken\""
		OpenID       *string                "json:\"openid\""
		Profile      map[string]interface{} "json:\"profile\""
		MappedEmail  *string                "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool "json:\"resultNull\""
		wechatUserObservation
		Data     map[string]interface{}     "json:\"data\""
		Requests []wechatRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "wechat.getUserInfo (no provider email)", Title: "returns null when the token carries no openid", Operation: "getUserInfo", Input: struct {
	ClientID     string                 "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	AccessToken  string                 "json:\"accessToken\""
	OpenID       *string                "json:\"openid\""
	Profile      map[string]interface{} "json:\"profile\""
	MappedEmail  *string                "json:\"mappedEmail\""
}{ClientID: "wx-app", ClientSecret: "wx-secret", AccessToken: "access-token"}, Observation: struct {
	ResultNull bool "json:\"resultNull\""
	wechatUserObservation
	Data     map[string]interface{}     "json:\"data\""
	Requests []wechatRequestObservation "json:\"requests\""
}{ResultNull: true, Requests: []wechatRequestObservation{}}}, struct {
	ID        string "json:\"id\""
	File      string "json:\"file\""
	Suite     string "json:\"suite\""
	Title     string "json:\"title\""
	Operation string "json:\"operation\""
	Input     struct {
		ClientID     string                 "json:\"clientId\""
		ClientSecret string                 "json:\"clientSecret\""
		AccessToken  string                 "json:\"accessToken\""
		OpenID       *string                "json:\"openid\""
		Profile      map[string]interface{} "json:\"profile\""
		MappedEmail  *string                "json:\"mappedEmail\""
	} "json:\"input\""
	Observation struct {
		ResultNull bool "json:\"resultNull\""
		wechatUserObservation
		Data     map[string]interface{}     "json:\"data\""
		Requests []wechatRequestObservation "json:\"requests\""
	} "json:\"observation\""
}{Suite: "wechat.getUserInfo (no provider email)", Title: "synthesizes a non-routable placeholder email keyed to unionid", Operation: "getUserInfo", Input: struct {
	ClientID     string                 "json:\"clientId\""
	ClientSecret string                 "json:\"clientSecret\""
	AccessToken  string                 "json:\"accessToken\""
	OpenID       *string                "json:\"openid\""
	Profile      map[string]interface{} "json:\"profile\""
	MappedEmail  *string                "json:\"mappedEmail\""
}{ClientID: "wx-app", ClientSecret: "wx-secret", AccessToken: "access-token", OpenID: fixturePointer("open-123"), Profile: map[string]interface{}{"headimgurl": "https://example.com/avatar.png", "nickname": "WeChat User", "openid": "open-123", "unionid": "union-abc"}}, Observation: struct {
	ResultNull bool "json:\"resultNull\""
	wechatUserObservation
	Data     map[string]interface{}     "json:\"data\""
	Requests []wechatRequestObservation "json:\"requests\""
}{wechatUserObservation: wechatUserObservation{ID: fixturePointer("union-abc"), Name: fixturePointer("WeChat User"), Email: fixturePointer("union-abc@wechat.invalid"), Image: fixturePointer("https://example.com/avatar.png"), EmailVerified: fixturePointer(false)}, Data: map[string]interface{}{"headimgurl": "https://example.com/avatar.png", "nickname": "WeChat User", "openid": "open-123", "unionid": "union-abc"}, Requests: []wechatRequestObservation{wechatRequestObservation{URL: "https://api.weixin.qq.com/sns/userinfo?access_token=access-token&openid=open-123&lang=zh_CN", Method: "GET"}}}}}
