package core

func cookieBehaviorCases() []cookiesBehaviorVector {
	return []cookiesBehaviorVector{
		{Suite: "Cookie Cache Field Filtering", Title: "should correctly filter multiple user fields based on returned config"},
		{Suite: "Cookie Cache Field Filtering", Title: "should default to JWT strategy when not specified"},
		{Suite: "Cookie Cache Field Filtering", Title: "should exclude user fields with returned: false from cookie cache"},
		{Suite: "Cookie Cache Field Filtering", Title: "should include unknown user fields for backward compatibility"},
		{Suite: "Cookie Cache Field Filtering", Title: "should maintain session field filtering (regression check)"},
		{Suite: "Cookie Cache Field Filtering", Title: "should reduce cookie size when large fields are excluded"},
		{Suite: "Cookie Cache Field Filtering", Title: "should return null for invalid JWT token"},
		{Suite: "Cookie Cache Field Filtering", Title: "should work with JWT strategy"},
		{Suite: "Cookie Cache Field Filtering", Title: "should work with compact strategy"},
		{Suite: "Cookie Chunking", Title: "should NOT chunk cookies when they are under 4KB"},
		{Suite: "Cookie Chunking", Title: "should chunk cookies when they exceed 4KB"},
		{Suite: "Cookie Chunking", Title: "should chunk session cache when attributes push the line over the limit"},
		{Suite: "Cookie Chunking", Title: "should clean up all chunks when deleting session"},
		{Suite: "Cookie Chunking", Title: "should reconstruct chunked cookies correctly"},
		{Suite: "Cookie Chunking", Title: "skips the session cache and warns when it is too large to chunk"},
		{Suite: "Cookie Chunking", Title: "skips the session cache and warns when the prefix alone overflows"},
		{Suite: "Cookie header without whitespace after semicolon", Title: "getChunkedCookie reconstructs chunks across `;`-only separators"},
		{Suite: "Cookie header without whitespace after semicolon", Title: "getSessionCookie finds the session cookie when separator is `;` only"},
		{Suite: "Cookie header without whitespace after semicolon", Title: "parseCookies returns each pair when separator is `;` only"},
		{Suite: "Cookie header without whitespace after semicolon", Title: "parseCookies tolerates mixed `;`, `; `, and `;\\t` separators"},
		{Suite: "account cookie sync on user switch", Title: "keeps the fresh account cookie issued for the new user when the request carries another user's stale account cookie"},
		{Suite: "account cookie sync on user switch", Title: "still expires another user's stale account cookie when the response issues no fresh one"},
		{Suite: "applySetCookies", Title: "last-wins on duplicate cookie name (existing + new)"},
		{Suite: "applySetCookies", Title: "merges into empty Cookie header"},
		{Suite: "applySetCookies", Title: "merges multiple Set-Cookie values"},
		{Suite: "applySetCookies", Title: "re-encodes Set-Cookie values containing reserved bytes on wire join"},
		{Suite: "applySetCookies", Title: "strips RFC 6265 quoted-string wrapping from Set-Cookie values"},
		{Suite: "applySetCookies", Title: "strips Set-Cookie attributes (only name=value lands)"},
		{Suite: "cookie configuration", Title: "should return correct cookie options based on configuration"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "converts parsed cookie attributes into cookie options"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "decodes URI-encoded cookie values"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles Expires when cookie value contains gmt substring"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles Expires with commas and multiple cookies"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles RFC 850 date format"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles asctime date format (no comma in date)"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles cookie with Expires followed by cookie without Expires"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles mixed cookies with and without Expires"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "handles non-standard Expires=0"},
		{Suite: "cookie-utils parseSetCookieHeader", Title: "parses partitioned as a boolean cookie attribute"},
		{Suite: "cookie-utils setRequestCookie", Title: "ignores malformed pairs in the existing header"},
		{Suite: "cookie-utils setRequestCookie", Title: "percent-encodes reserved cookie-octet bytes when serializing"},
		{Suite: "cookie-utils setRequestCookie", Title: "preserves existing cookies and joins with `; ` per RFC 6265"},
		{Suite: "cookie-utils setRequestCookie", Title: "replaces an existing cookie of the same name rather than duplicating it"},
		{Suite: "cookie-utils setRequestCookie", Title: "treats input as semantic and percent-encodes literal double-quotes"},
		{Suite: "cookie-utils setRequestCookie", Title: "writes a cookie when the header is empty"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should handle cookie names that are exactly the prefix"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should handle cookie names with dots and special characters"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should handle cookie names with prefix-like strings in the middle"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should handle empty string"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should prioritize __Secure- prefix over __Host- prefix"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should return cookie name unchanged if no prefix"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should strip __Host- prefix from cookie name"},
		{Suite: "cookie-utils stripSecureCookiePrefix", Title: "should strip __Secure- prefix from cookie name"},
		{Suite: "cookies > production environment", Title: "should use secure cookies when baseURL is not configured"},
		{Suite: "cookies", Title: "should set cookies with default options"},
		{Suite: "cookies", Title: "should set multiple cookies"},
		{Suite: "cookies", Title: "should use secure cookies"},
		{Suite: "cookies", Title: "should use secure cookies when the base url is https"},
		{Suite: "crossSubdomainCookies", Title: "should update cookies with custom domain"},
		{Suite: "crossSubdomainCookies", Title: "should use default domain from baseURL if not provided"},
		{Suite: "expireCookie", Title: "preserves attributes"},
		{Suite: "expireCookie", Title: "scrubs collapsed Set-Cookie headers when getSetCookie is unavailable"},
		{Suite: "getCookieCache expiry (compact strategy)", Title: "returns null when the cache window has elapsed"},
		{Suite: "getCookieCache expiry (compact strategy)", Title: "returns null when the embedded session has expired"},
		{Suite: "getCookieCache expiry (compact strategy)", Title: "returns the session for a fresh snapshot"},
		{Suite: "getSessionCookie > with '-' separator > with  prefix (regular)", Title: "finds cookie with config {\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '-' separator > with  prefix (regular)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\",\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '-' separator > with  prefix (regular)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\"}"},
		{Suite: "getSessionCookie > with '-' separator > with  prefix (regular)", Title: "finds cookie with config {}"},
		{Suite: "getSessionCookie > with '-' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '-' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\",\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '-' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\"}"},
		{Suite: "getSessionCookie > with '-' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {}"},
		{Suite: "getSessionCookie > with '.' separator > with  prefix (regular)", Title: "finds cookie with config {\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '.' separator > with  prefix (regular)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\",\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '.' separator > with  prefix (regular)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\"}"},
		{Suite: "getSessionCookie > with '.' separator > with  prefix (regular)", Title: "finds cookie with config {}"},
		{Suite: "getSessionCookie > with '.' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '.' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\",\"cookieName\":\"my_token\"}"},
		{Suite: "getSessionCookie > with '.' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {\"cookiePrefix\":\"myprefix\"}"},
		{Suite: "getSessionCookie > with '.' separator > with __Secure- prefix (secure)", Title: "finds cookie with config {}"},
		{Suite: "getSessionCookie", Title: "does not fall back to a non-secure cookie when the __Secure- value is empty"},
		{Suite: "getSessionCookie", Title: "prefers the __Secure- cookie when a non-secure leftover is also present"},
		{Suite: "getSessionCookie", Title: "should allow override cookie name"},
		{Suite: "getSessionCookie", Title: "should allow override cookie prefix with secure cookies"},
		{Suite: "getSessionCookie", Title: "should chunk large cookies instead of logging error"},
		{Suite: "getSessionCookie", Title: "should respect dontRememberMe when storing session in cookie cache"},
		{Suite: "getSessionCookie", Title: "should return cookie cache"},
		{Suite: "getSessionCookie", Title: "should return null if the cookie is invalid"},
		{Suite: "getSessionCookie", Title: "should return the correct session cookie"},
		{Suite: "getSessionCookie", Title: "should return the correct session cookie on production"},
		{Suite: "getSessionCookie", Title: "should throw an error if the secret is not provided"},
		{Suite: "getSessionCookie", Title: "should work with Headers object directly"},
		{Suite: "getSessionCookie", Title: "should work with Headers-like object that has inherited 'headers' property"},
		{Suite: "getSessionCookie", Title: "should work with cross-realm Headers-like object (instanceof fails)"},
		{Suite: "parse cookies", Title: "should parse cookies into key-value map"},
		{Suite: "parse cookies", Title: "should securely parse the signed cookies with padding"},
		{Suite: "parseCookies validation", Title: "accepts values with space and comma (real-world deviation)"},
		{Suite: "parseCookies validation", Title: "rejects entries with CR/LF in raw key or value (no trim escape)"},
		{Suite: "parseCookies validation", Title: "rejects names containing characters outside RFC 7230 token"},
		{Suite: "parseCookies validation", Title: "rejects values containing control chars, double-quote, or backslash"},
		{Suite: "parseCookies validation", Title: "returns empty map for empty header"},
		{Suite: "parseCookies validation", Title: "splits on first `=` only, preserving subsequent `=` in value"},
		{Suite: "parseCookies validation", Title: "strips double-quoted values per RFC 6265 §4.1.1"},
		{Suite: "sensitive session middleware cookie cache", Title: "should not let request query re-enable cookie cache on sensitive endpoints"},
	}
}
