// Command facadegen generates the root singleauth compatibility facade from
// the exported declarations in package core.
package main

import (
	"bytes"
	"errors"
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/printer"
	"go/token"
	"os"
	"path"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
)

const generatedHeader = "// Code generated by go generate; DO NOT EDIT.\n\n"

type options struct {
	coreDir     string
	output      string
	packageName string
	coreImport  string
}

type declaration struct {
	name string
	doc  string
}

type typeDeclaration struct {
	declaration
	file       *ast.File
	typeParams *ast.FieldList
}

type valueDeclaration struct {
	declaration
	token token.Token
}

type funcDeclaration struct {
	declaration
	file     *ast.File
	funcType *ast.FuncType
}

type importReference struct {
	name string
	path string
}

type facade struct {
	fset   *token.FileSet
	types  []typeDeclaration
	values []valueDeclaration
	funcs  []funcDeclaration
}

func main() {
	var config options
	flag.StringVar(&config.coreDir, "core", "core", "directory containing the core package")
	flag.StringVar(&config.output, "output", "facade_gen.go", "generated facade path")
	flag.StringVar(&config.packageName, "package", "singleauth", "generated package name")
	flag.StringVar(&config.coreImport, "core-import", "", "core package import path (derived from go.mod when empty)")
	flag.Parse()

	if config.coreImport == "" {
		modulePath, err := readModulePath("go.mod")
		if err != nil {
			fatal(err)
		}
		config.coreImport = strings.TrimSuffix(modulePath, "/") + "/core"
	}

	source, err := generate(config)
	if err != nil {
		fatal(err)
	}
	if err := os.WriteFile(config.output, source, 0o644); err != nil {
		fatal(fmt.Errorf("write facade: %w", err))
	}
}

func fatal(err error) {
	fmt.Fprintln(os.Stderr, "facadegen:", err)
	os.Exit(1)
}

func generate(config options) ([]byte, error) {
	parsed, err := parseCore(config.coreDir)
	if err != nil {
		return nil, err
	}

	var output bytes.Buffer
	output.WriteString(generatedHeader)
	output.WriteString("package ")
	output.WriteString(config.packageName)
	output.WriteString("\n\n")

	imports, err := collectFacadeImports(parsed.types, parsed.funcs)
	if err != nil {
		return nil, err
	}
	if _, exists := imports["core"]; exists {
		return nil, errors.New("an exported function signature reserves the import name core")
	}
	imports["core"] = importReference{name: "core", path: config.coreImport}
	writeImports(&output, imports)

	if len(parsed.types) != 0 {
		output.WriteString("// Types exported by the core runtime.\n")
		for _, declaration := range parsed.types {
			writeDoc(&output, declaration.doc)
			output.WriteString("type ")
			output.WriteString(declaration.name)
			if declaration.typeParams != nil {
				params, printErr := printTypeParameters(parsed.fset, declaration.typeParams)
				if printErr != nil {
					return nil, printErr
				}
				output.WriteString(params)
			}
			output.WriteString(" = core.")
			output.WriteString(declaration.name)
			output.WriteString(typeArguments(declaration.typeParams))
			output.WriteString("\n\n")
		}
	}

	writeValues(&output, parsed.values, token.CONST, "Constants exported by the core runtime.")
	writeValues(&output, parsed.values, token.VAR, "Variables exported by the core runtime.")

	if len(parsed.funcs) != 0 {
		output.WriteString("// Functions exported by the core runtime.\n")
		for _, declaration := range parsed.funcs {
			writeDoc(&output, declaration.doc)
			if err := writeFunction(&output, parsed.fset, declaration); err != nil {
				return nil, err
			}
			output.WriteByte('\n')
		}
	}

	formatted, err := format.Source(output.Bytes())
	if err != nil {
		return nil, fmt.Errorf("format generated facade: %w\n%s", err, output.String())
	}
	return formatted, nil
}

func parseCore(directory string) (facade, error) {
	entries, err := os.ReadDir(directory)
	if err != nil {
		return facade{}, fmt.Errorf("read core directory: %w", err)
	}
	sort.Slice(entries, func(left, right int) bool { return entries[left].Name() < entries[right].Name() })

	result := facade{fset: token.NewFileSet()}
	seen := make(map[string]string)
	for _, entry := range entries {
		name := entry.Name()
		if entry.IsDir() || !strings.HasSuffix(name, ".go") || strings.HasSuffix(name, "_test.go") {
			continue
		}
		filename := filepath.Join(directory, name)
		file, parseErr := parser.ParseFile(result.fset, filename, nil, parser.ParseComments)
		if parseErr != nil {
			return facade{}, fmt.Errorf("parse %s: %w", filename, parseErr)
		}
		if file.Name.Name != "core" {
			return facade{}, fmt.Errorf("%s declares package %s, want core", filename, file.Name.Name)
		}
		for _, item := range file.Decls {
			switch declaration := item.(type) {
			case *ast.GenDecl:
				if err := collectGeneralDeclaration(&result, file, declaration, seen); err != nil {
					return facade{}, fmt.Errorf("%s: %w", filename, err)
				}
			case *ast.FuncDecl:
				if declaration.Recv != nil || !ast.IsExported(declaration.Name.Name) {
					continue
				}
				if err := recordName(seen, declaration.Name.Name, "function"); err != nil {
					return facade{}, fmt.Errorf("%s: %w", filename, err)
				}
				result.funcs = append(result.funcs, funcDeclaration{
					declaration: declarationInfo(declaration.Name.Name, declaration.Doc),
					file:        file,
					funcType:    declaration.Type,
				})
			}
		}
	}

	sort.Slice(result.types, func(left, right int) bool { return result.types[left].name < result.types[right].name })
	sort.Slice(result.values, func(left, right int) bool {
		if result.values[left].token != result.values[right].token {
			return result.values[left].token < result.values[right].token
		}
		return result.values[left].name < result.values[right].name
	})
	sort.Slice(result.funcs, func(left, right int) bool { return result.funcs[left].name < result.funcs[right].name })
	return result, nil
}

func collectGeneralDeclaration(
	result *facade,
	file *ast.File,
	declaration *ast.GenDecl,
	seen map[string]string,
) error {
	switch declaration.Tok {
	case token.TYPE:
		for _, item := range declaration.Specs {
			specification, ok := item.(*ast.TypeSpec)
			if !ok || !ast.IsExported(specification.Name.Name) {
				continue
			}
			if err := recordName(seen, specification.Name.Name, "type"); err != nil {
				return err
			}
			result.types = append(result.types, typeDeclaration{
				declaration: declarationInfo(
					specification.Name.Name,
					firstComment(specification.Doc, declaration.Doc),
				),
				file:       file,
				typeParams: specification.TypeParams,
			})
		}
	case token.CONST, token.VAR:
		for _, item := range declaration.Specs {
			specification, ok := item.(*ast.ValueSpec)
			if !ok {
				continue
			}
			doc := firstComment(specification.Doc, declaration.Doc)
			for _, identifier := range specification.Names {
				if !ast.IsExported(identifier.Name) {
					continue
				}
				kind := strings.ToLower(declaration.Tok.String())
				if err := recordName(seen, identifier.Name, kind); err != nil {
					return err
				}
				result.values = append(result.values, valueDeclaration{
					declaration: declarationInfo(identifier.Name, doc),
					token:       declaration.Tok,
				})
			}
		}
	}
	return nil
}

func recordName(seen map[string]string, name, kind string) error {
	if previous, exists := seen[name]; exists {
		return fmt.Errorf("exported name %s is both %s and %s", name, previous, kind)
	}
	seen[name] = kind
	return nil
}

func declarationInfo(name string, comments *ast.CommentGroup) declaration {
	return declaration{name: name, doc: rawComment(comments)}
}

func firstComment(comments ...*ast.CommentGroup) *ast.CommentGroup {
	for _, comment := range comments {
		if comment != nil {
			return comment
		}
	}
	return nil
}

func rawComment(group *ast.CommentGroup) string {
	if group == nil {
		return ""
	}
	var output strings.Builder
	for _, comment := range group.List {
		output.WriteString(comment.Text)
		output.WriteByte('\n')
	}
	return output.String()
}

func collectFacadeImports(
	types []typeDeclaration,
	functions []funcDeclaration,
) (map[string]importReference, error) {
	imports := make(map[string]importReference)
	paths := make(map[string]string)
	for _, declaration := range types {
		if declaration.typeParams == nil {
			continue
		}
		if err := collectNodeImports(declaration.file, declaration.typeParams, imports, paths); err != nil {
			return nil, err
		}
	}
	for _, function := range functions {
		if err := collectNodeImports(function.file, function.funcType, imports, paths); err != nil {
			return nil, err
		}
	}
	return imports, nil
}

func collectNodeImports(
	file *ast.File,
	node ast.Node,
	imports map[string]importReference,
	paths map[string]string,
) error {
	available, err := fileImports(file)
	if err != nil {
		return err
	}
	used := make(map[string]struct{})
	ast.Inspect(node, func(node ast.Node) bool {
		selector, ok := node.(*ast.SelectorExpr)
		if !ok {
			return true
		}
		identifier, ok := selector.X.(*ast.Ident)
		if ok {
			used[identifier.Name] = struct{}{}
		}
		return true
	})
	for name := range used {
		reference, exists := available[name]
		if !exists {
			continue
		}
		if previous, exists := imports[name]; exists && previous.path != reference.path {
			return fmt.Errorf("import name %s maps to both %s and %s", name, previous.path, reference.path)
		}
		if previousName, exists := paths[reference.path]; exists && previousName != name {
			return fmt.Errorf("import path %s is used as both %s and %s", reference.path, previousName, name)
		}
		imports[name] = reference
		paths[reference.path] = name
	}
	return nil
}

func fileImports(file *ast.File) (map[string]importReference, error) {
	result := make(map[string]importReference)
	for _, specification := range file.Imports {
		importPath, err := strconv.Unquote(specification.Path.Value)
		if err != nil {
			return nil, fmt.Errorf("decode import %s: %w", specification.Path.Value, err)
		}
		name := path.Base(importPath)
		if specification.Name != nil {
			name = specification.Name.Name
		}
		if name == "_" || name == "." {
			continue
		}
		result[name] = importReference{name: name, path: importPath}
	}
	return result, nil
}

func writeImports(output *bytes.Buffer, imports map[string]importReference) {
	names := make([]string, 0, len(imports))
	for name := range imports {
		names = append(names, name)
	}
	sort.Slice(names, func(left, right int) bool {
		leftReference := imports[names[left]]
		rightReference := imports[names[right]]
		leftStandard := standardLibraryImport(leftReference.path)
		rightStandard := standardLibraryImport(rightReference.path)
		if leftStandard != rightStandard {
			return leftStandard
		}
		if leftReference.path != rightReference.path {
			return leftReference.path < rightReference.path
		}
		return leftReference.name < rightReference.name
	})

	output.WriteString("import (\n")
	previousStandard := true
	for _, name := range names {
		reference := imports[name]
		standard := standardLibraryImport(reference.path)
		if !standard && previousStandard {
			output.WriteByte('\n')
		}
		output.WriteByte('\t')
		if reference.name != path.Base(reference.path) || reference.name == "core" {
			output.WriteString(reference.name)
			output.WriteByte(' ')
		}
		output.WriteString(strconv.Quote(reference.path))
		output.WriteByte('\n')
		previousStandard = standard
	}
	output.WriteString(")\n\n")
}

func standardLibraryImport(importPath string) bool {
	first, _, _ := strings.Cut(importPath, "/")
	return !strings.Contains(first, ".")
}

func writeValues(output *bytes.Buffer, values []valueDeclaration, kind token.Token, heading string) {
	hasValues := false
	for _, declaration := range values {
		if declaration.token == kind {
			hasValues = true
			break
		}
	}
	if !hasValues {
		return
	}
	output.WriteString("// ")
	output.WriteString(heading)
	output.WriteByte('\n')
	for _, declaration := range values {
		if declaration.token != kind {
			continue
		}
		writeDoc(output, declaration.doc)
		output.WriteString(kind.String())
		output.WriteByte(' ')
		output.WriteString(declaration.name)
		output.WriteString(" = core.")
		output.WriteString(declaration.name)
		output.WriteString("\n\n")
	}
}

func writeDoc(output *bytes.Buffer, doc string) {
	if doc == "" {
		return
	}
	output.WriteString(doc)
	if !strings.HasSuffix(doc, "\n") {
		output.WriteByte('\n')
	}
}

func writeFunction(
	output *bytes.Buffer,
	fset *token.FileSet,
	declaration funcDeclaration,
) error {
	arguments := nameParameters(declaration.funcType.Params)
	signature, err := printNode(fset, declaration.funcType)
	if err != nil {
		return err
	}
	if !strings.HasPrefix(signature, "func") {
		return fmt.Errorf("render function %s: malformed signature %q", declaration.name, signature)
	}

	output.WriteString("func ")
	output.WriteString(declaration.name)
	output.WriteString(strings.TrimPrefix(signature, "func"))
	output.WriteString(" {\n\t")
	if declaration.funcType.Results != nil && len(declaration.funcType.Results.List) != 0 {
		output.WriteString("return ")
	}
	output.WriteString("core.")
	output.WriteString(declaration.name)
	output.WriteString(typeArguments(declaration.funcType.TypeParams))
	output.WriteByte('(')
	for index, argument := range arguments {
		if index != 0 {
			output.WriteString(", ")
		}
		output.WriteString(argument)
	}
	output.WriteString(")\n}\n")
	return nil
}

func nameParameters(parameters *ast.FieldList) []string {
	if parameters == nil {
		return nil
	}
	arguments := make([]string, 0, parameters.NumFields())
	sequence := 0
	for fieldIndex, field := range parameters.List {
		if len(field.Names) == 0 {
			field.Names = []*ast.Ident{ast.NewIdent(fmt.Sprintf("arg%d", sequence))}
			sequence++
		}
		for nameIndex, identifier := range field.Names {
			if identifier.Name == "_" {
				identifier = ast.NewIdent(fmt.Sprintf("arg%d", sequence))
				field.Names[nameIndex] = identifier
				sequence++
			}
			argument := identifier.Name
			if fieldIndex == len(parameters.List)-1 &&
				nameIndex == len(field.Names)-1 {
				if _, variadic := field.Type.(*ast.Ellipsis); variadic {
					argument += "..."
				}
			}
			arguments = append(arguments, argument)
		}
	}
	return arguments
}

func typeArguments(parameters *ast.FieldList) string {
	if parameters == nil || len(parameters.List) == 0 {
		return ""
	}
	names := make([]string, 0, parameters.NumFields())
	for _, field := range parameters.List {
		for _, identifier := range field.Names {
			names = append(names, identifier.Name)
		}
	}
	return "[" + strings.Join(names, ", ") + "]"
}

func printNode(fset *token.FileSet, node any) (string, error) {
	var output bytes.Buffer
	config := printer.Config{Mode: printer.UseSpaces | printer.TabIndent, Tabwidth: 8}
	if err := config.Fprint(&output, fset, node); err != nil {
		return "", fmt.Errorf("print declaration: %w", err)
	}
	return output.String(), nil
}

func printTypeParameters(fset *token.FileSet, parameters *ast.FieldList) (string, error) {
	if parameters == nil || len(parameters.List) == 0 {
		return "", nil
	}
	signature, err := printNode(fset, &ast.FuncType{
		TypeParams: parameters,
		Params:     &ast.FieldList{},
	})
	if err != nil {
		return "", err
	}
	if !strings.HasPrefix(signature, "func") || !strings.HasSuffix(signature, "()") {
		return "", fmt.Errorf("render type parameters: malformed signature %q", signature)
	}
	return strings.TrimSuffix(strings.TrimPrefix(signature, "func"), "()"), nil
}

func readModulePath(filename string) (string, error) {
	contents, err := os.ReadFile(filename)
	if err != nil {
		return "", fmt.Errorf("read %s: %w", filename, err)
	}
	for _, line := range strings.Split(string(contents), "\n") {
		fields := strings.Fields(line)
		if len(fields) == 2 && fields[0] == "module" {
			return fields[1], nil
		}
	}
	return "", fmt.Errorf("%s does not declare a module path", filename)
}
