package oauthprovider

import "encoding/json"

func pointerTo[T any](value T) *T {
	return &value
}

var basicAuthCases = []basicAuthCase{{Title: "keeps a trailing colon as part of client_secret", Input: basicAuthInput{Authorization: "Basic Y2lkOnNlY3JldDo="},
	Observation: ClientCredentials{ClientID: "cid", ClientSecret: "secret:"}},
	{Title: "preserves colons inside client_secret per RFC 7617", Input: basicAuthInput{Authorization: "Basic Y2lkOnBhOnNzOndvcmQ="},
		Observation: ClientCredentials{ClientID: "cid", ClientSecret: "pa:ss:word"}}}
var consentCases = []consentCase{{Title: "should allow scopes change to client", Observation: consentObservation{Status: 200, Scopes: []string{"email"},
	IdentityPreserved: true, CreatedAtPreserved: true, UpdatedAtIsWholeSecond: true}},
	{Title: "should create a tester consents", Observation: consentObservation{FirstClientMatches: true, FirstUserMatches: true, FirstScopes: []string{"profile"},
		SecondClientMatches: true, SecondUserMatches: true, SecondScopes: []string{"openid",
			"profile"},
		TimestampsAreWholeSeconds: true}},
	{Title: "should delete the consent", Observation: consentObservation{Status: 200, DataIsNull: true, Removed: true}},
	{Title: "should get a specific consent", Observation: consentObservation{Status: 200, MatchesCreatedConsent: true}},
	{Title: "should get user's consents", Observation: consentObservation{Status: 200, Count: 2, OrderMatches: true}},
	{Title: "should not allow updates to scopes not granted to client", Observation: consentObservation{Status: 400}},
	{Title: "should reject updates to a consent owned by another user", Observation: consentObservation{Status: 401}}}
var logoutCases = []logoutCase{{Suite: "oauth logout - disableJwtPlugin", Title: "should pass for clients with enable_end_session access", Observation: logoutObservation{Status: 200, DataIsNull: true, ErrorIsNull: true, SIDPresent: true, SIDMatchesSession: true, SessionRemoved: true, TokenShape: logoutTokenShape{AccessToken: true, IDToken: true, RefreshToken: true, Scope: "openid email profile offline_access"}}},
	{Suite: "oauth logout - disableJwtPlugin", Title: "should pass with redirection", Observation: logoutObservation{Status: 302, SIDPresent: true, Location: "http://localhost:5000/api/auth/oauth2/callback/logout"}},
	{Suite: "oauth logout", Title: "should fail for clients without enable_end_session access", Observation: logoutObservation{Status: 401, TokenShape: logoutTokenShape{AccessToken: true, IDToken: true, RefreshToken: true, Scope: "openid email profile offline_access"}}},
	{Suite: "oauth logout", Title: "should fail with invalid id_token_hint", Observation: logoutObservation{Status: 401}},
	{Suite: "oauth logout", Title: "should not allow registration of rp-initiated clients, specifically enable_end_session", Observation: logoutObservation{Status: 200, ClientID: true, UserID: true, ClientSecret: true, RedirectURIs: []string{"http://localhost:5000/api/auth/oauth2/callback/test"},
		PostLogoutRedirectURIs: []string{"http://localhost:5000/api/auth/oauth2/callback/logout"}}},
	{Suite: "oauth logout", Title: "should pass for clients with enable_end_session access", Observation: logoutObservation{Status: 200, DataIsNull: true, ErrorIsNull: true, SIDPresent: true, SIDMatchesSession: true, SessionRemoved: true, TokenShape: logoutTokenShape{AccessToken: true, IDToken: true, RefreshToken: true, Scope: "openid email profile offline_access"}}},
	{Suite: "oauth logout", Title: "should pass with redirection", Observation: logoutObservation{Status: 302, SIDPresent: true, Location: "http://localhost:5000/api/auth/oauth2/callback/logout?state=123"}}}
var mcpCases = []mcpCase{{Suite: "mcp", Title: "should provide the correct metadata using resource: 'http://localhost:5000'", Observation: map[string]any{"expectedChallenge": "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource\"",
	"handlerChallenge": "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource\"",
	"handlerStatus":    float64(401),
	"verifyChallenge":  "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource\"",
	"verifyStatus":     float64(401)}},
	{Suite: "mcp", Title: "should provide the correct metadata using resource: 'http://localhost:5000/resource1'", Observation: map[string]any{"expectedChallenge": "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource/resource1\"",
		"handlerChallenge": "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource/resource1\"",
		"handlerStatus":    float64(401),
		"verifyChallenge":  "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource/resource1\"",
		"verifyStatus":     float64(401)}},
	{Suite: "mcp", Title: "should provide the correct metadata using resource: [ 'http://localhost:5000', …(1) ]", Observation: map[string]any{"expectedChallenge": "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource\", Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource/resource1\"",
		"handlerChallenge": "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource\", Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource/resource1\"",
		"handlerStatus":    float64(401),
		"verifyChallenge":  "Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource\", Bearer resource_metadata=\"http://localhost:5000/.well-known/oauth-protected-resource/resource1\"",
		"verifyStatus":     float64(401)}}}
var metadataCases = []metadataCase{{Suite: "dynamic baseURL metadata wrappers", Title: "oauthProviderAuthServerMetadata resolves baseURL from the incoming request", Observation: map[string]any{"cacheControl": "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",
	"contentType": "application/json",
	"issuer":      "https://tenant.example.com/api/auth",
	"status":      float64(200)}},
	{Suite: "dynamic baseURL metadata wrappers", Title: "oauthProviderOpenIdConfigMetadata resolves baseURL from the incoming request", Observation: map[string]any{"cacheControl": "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",
		"contentType": "application/json",
		"issuer":      "https://tenant.example.com/api/auth",
		"status":      float64(200)}},
	{Suite: "oauth metadata", Title: "should advertise custom claims", Observation: map[string]any{"claims": []any{"sub",
		"iss",
		"aud",
		"exp",
		"iat",
		"sid",
		"scope",
		"azp",
		"email",
		"email_verified",
		"name",
		"picture",
		"family_name",
		"given_name",
		"http://example.com/roles"},
		"oauthClaims": []any{"sub",
			"iss",
			"aud",
			"exp",
			"iat",
			"sid",
			"scope",
			"azp",
			"email",
			"email_verified",
			"name",
			"picture",
			"family_name",
			"given_name",
			"http://example.com/roles"}}},
	{Suite: "oauth metadata", Title: "should advertise dynamic client registration from direct OAuth metadata when enabled", Observation: map[string]any{"cacheControl": "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",
		"contentType":          "application/json",
		"issuer":               "http://localhost:3000/api/auth",
		"registrationEndpoint": "http://localhost:3000/api/auth/oauth2/register",
		"status":               float64(200)}},
	{Suite: "oauth metadata", Title: "should fail if advertised scope invalid", Observation: map[string]any{"errorMessage": "advertisedMetadata.scopes_supported create:test not found in scopes",
		"errorName": "ReferenceError"}},
	{Suite: "oauth metadata", Title: "should get openid, equivalent auth server", Observation: map[string]any{"oauth": map[string]any{"acr_values_supported": []any{"urn:mace:incommon:iap:bronze"},
		"authorization_endpoint":                         "http://localhost:3000/api/auth/oauth2/authorize",
		"authorization_response_iss_parameter_supported": true,
		"claims_supported": []any{"sub",
			"iss",
			"aud",
			"exp",
			"iat",
			"sid",
			"scope",
			"azp",
			"email",
			"email_verified",
			"name",
			"picture",
			"family_name",
			"given_name"},
		"code_challenge_methods_supported": []any{"S256"},
		"end_session_endpoint":             "http://localhost:3000/api/auth/oauth2/end-session",
		"grant_types_supported": []any{"authorization_code",
			"client_credentials",
			"refresh_token"},
		"id_token_signing_alg_values_supported": []any{"EdDSA"},
		"introspection_endpoint":                "http://localhost:3000/api/auth/oauth2/introspect",
		"introspection_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"issuer":   "http://localhost:3000/api/auth",
		"jwks_uri": "http://localhost:3000/api/auth/jwks",
		"prompt_values_supported": []any{"login",
			"consent",
			"create",
			"select_account",
			"none"},
		"registration_endpoint":    "http://localhost:3000/api/auth/oauth2/register",
		"response_modes_supported": []any{"query"},
		"response_types_supported": []any{"code"},
		"revocation_endpoint":      "http://localhost:3000/api/auth/oauth2/revoke",
		"revocation_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"scopes_supported": []any{"openid",
			"profile",
			"email",
			"offline_access"},
		"subject_types_supported": []any{"public"},
		"token_endpoint":          "http://localhost:3000/api/auth/oauth2/token",
		"token_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"userinfo_endpoint": "http://localhost:3000/api/auth/oauth2/userinfo"},
		"openID": map[string]any{"acr_values_supported": []any{"urn:mace:incommon:iap:bronze"},
			"authorization_endpoint":                         "http://localhost:3000/api/auth/oauth2/authorize",
			"authorization_response_iss_parameter_supported": true,
			"claims_supported": []any{"sub",
				"iss",
				"aud",
				"exp",
				"iat",
				"sid",
				"scope",
				"azp",
				"email",
				"email_verified",
				"name",
				"picture",
				"family_name",
				"given_name"},
			"code_challenge_methods_supported": []any{"S256"},
			"end_session_endpoint":             "http://localhost:3000/api/auth/oauth2/end-session",
			"grant_types_supported": []any{"authorization_code",
				"client_credentials",
				"refresh_token"},
			"id_token_signing_alg_values_supported": []any{"EdDSA"},
			"introspection_endpoint":                "http://localhost:3000/api/auth/oauth2/introspect",
			"introspection_endpoint_auth_methods_supported": []any{"client_secret_basic",
				"client_secret_post"},
			"issuer":   "http://localhost:3000/api/auth",
			"jwks_uri": "http://localhost:3000/api/auth/jwks",
			"prompt_values_supported": []any{"login",
				"consent",
				"create",
				"select_account",
				"none"},
			"registration_endpoint":    "http://localhost:3000/api/auth/oauth2/register",
			"response_modes_supported": []any{"query"},
			"response_types_supported": []any{"code"},
			"revocation_endpoint":      "http://localhost:3000/api/auth/oauth2/revoke",
			"revocation_endpoint_auth_methods_supported": []any{"client_secret_basic",
				"client_secret_post"},
			"scopes_supported": []any{"openid",
				"profile",
				"email",
				"offline_access"},
			"subject_types_supported": []any{"public"},
			"token_endpoint":          "http://localhost:3000/api/auth/oauth2/token",
			"token_endpoint_auth_methods_supported": []any{"client_secret_basic",
				"client_secret_post"},
			"userinfo_endpoint": "http://localhost:3000/api/auth/oauth2/userinfo"}}},
	{Suite: "oauth metadata", Title: "should not have an openid-configuration, has auth server configuration", Observation: map[string]any{"oauth": map[string]any{"authorization_endpoint": "http://localhost:3000/api/auth/oauth2/authorize",
		"authorization_response_iss_parameter_supported": true,
		"code_challenge_methods_supported":               []any{"S256"},
		"grant_types_supported": []any{"authorization_code",
			"client_credentials",
			"refresh_token"},
		"introspection_endpoint": "http://localhost:3000/api/auth/oauth2/introspect",
		"introspection_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"issuer":                   "http://localhost:3000/api/auth",
		"jwks_uri":                 "http://localhost:3000/api/auth/jwks",
		"registration_endpoint":    "http://localhost:3000/api/auth/oauth2/register",
		"response_modes_supported": []any{"query"},
		"response_types_supported": []any{"code"},
		"revocation_endpoint":      "http://localhost:3000/api/auth/oauth2/revoke",
		"revocation_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"scopes_supported": []any{"create:test"},
		"token_endpoint":   "http://localhost:3000/api/auth/oauth2/token",
		"token_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"}},
		"openIDError": map[string]any{"code": nil,
			"message": "",
			"name":    "APIError",
			"status":  "NOT_FOUND"}}},
	{Suite: "oauth metadata", Title: "should not provide dynamic client registration endpoint when disabled", Observation: map[string]any{"oauthRegistrationPresent": false,
		"openIDRegistrationPresent": false}},
	{Suite: "oauth metadata", Title: "should not provide dynamic client registration endpoint when undefined", Observation: map[string]any{"oauthRegistrationPresent": false,
		"openIDRegistrationPresent": false}},
	{Suite: "oauth metadata", Title: "should only skip trailing slashes when configured", Observation: map[string]any{"defaultStatus": float64(404),
		"skipIssuer": "http://localhost:3000/api/auth",
		"skipStatus": float64(200)}},
	{Suite: "oauth metadata", Title: "should restrict direct metadata requests to GET and HEAD", Observation: map[string]any{"headBodies": []any{"",
		""},
		"headStatuses": []any{float64(200), float64(200)},
		"postAllows": []any{"GET, HEAD",
			"GET, HEAD",
			"GET, HEAD"},
		"postStatuses": []any{float64(405), float64(405), float64(405)}}},
	{Suite: "oauth metadata", Title: "should serve OIDC metadata at the direct issuer well-known URL", Observation: map[string]any{"cacheControl": "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",
		"contentType": "application/json",
		"issuer":      "http://localhost:3000/api/auth",
		"status":      float64(200)}},
	{Suite: "oauth metadata", Title: "should serve authorization server metadata at the RFC 8414 path-insertion URL", Observation: map[string]any{"cacheControl": "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",
		"contentType": "application/json",
		"issuer":      "http://localhost:3000/api/auth",
		"status":      float64(200)}},
	{Suite: "oauth metadata", Title: "should serve authorization server metadata at the issuer-appended well-known URL", Observation: map[string]any{"cacheControl": "public, max-age=15, stale-while-revalidate=15, stale-if-error=86400",
		"contentType": "application/json",
		"issuer":      "http://localhost:3000/api/auth",
		"status":      float64(200)}},
	{Suite: "oauth metadata", Title: "should support disableJwtPlugin", Observation: map[string]any{"jwksPresent": false,
		"oauthSigningAlgorithms": []any{"HS256"},
		"signingAlgorithms":      []any{"HS256"}}},
	{Suite: "oauth metadata", Title: "should use the remoteJwks url", Observation: map[string]any{"jwksURI": "http://example.com/.well-known/openid-configuration",
		"oauthJWKSURI":      "http://example.com/.well-known/openid-configuration",
		"signingAlgorithms": []any{"ES256"}}},
	{Suite: "oauth metadata", Title: "should utilize advertised metadata fields", Observation: map[string]any{"oauth": map[string]any{"acr_values_supported": []any{"urn:mace:incommon:iap:bronze"},
		"authorization_endpoint":                         "http://localhost:3000/api/auth/oauth2/authorize",
		"authorization_response_iss_parameter_supported": true,
		"claims_supported": []any{"sub",
			"iss",
			"aud",
			"exp",
			"iat",
			"scope"},
		"code_challenge_methods_supported": []any{"S256"},
		"end_session_endpoint":             "http://localhost:3000/api/auth/oauth2/end-session",
		"grant_types_supported": []any{"authorization_code",
			"client_credentials",
			"refresh_token"},
		"id_token_signing_alg_values_supported": []any{"EdDSA"},
		"introspection_endpoint":                "http://localhost:3000/api/auth/oauth2/introspect",
		"introspection_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"issuer":   "http://localhost:3000/api/auth",
		"jwks_uri": "http://localhost:3000/api/auth/jwks",
		"prompt_values_supported": []any{"login",
			"consent",
			"create",
			"select_account",
			"none"},
		"registration_endpoint":    "http://localhost:3000/api/auth/oauth2/register",
		"response_modes_supported": []any{"query"},
		"response_types_supported": []any{"code"},
		"revocation_endpoint":      "http://localhost:3000/api/auth/oauth2/revoke",
		"revocation_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"scopes_supported":        []any{"email"},
		"subject_types_supported": []any{"public"},
		"token_endpoint":          "http://localhost:3000/api/auth/oauth2/token",
		"token_endpoint_auth_methods_supported": []any{"client_secret_basic",
			"client_secret_post"},
		"userinfo_endpoint": "http://localhost:3000/api/auth/oauth2/userinfo"},
		"openID": map[string]any{"acr_values_supported": []any{"urn:mace:incommon:iap:bronze"},
			"authorization_endpoint":                         "http://localhost:3000/api/auth/oauth2/authorize",
			"authorization_response_iss_parameter_supported": true,
			"claims_supported": []any{"sub",
				"iss",
				"aud",
				"exp",
				"iat",
				"scope"},
			"code_challenge_methods_supported": []any{"S256"},
			"end_session_endpoint":             "http://localhost:3000/api/auth/oauth2/end-session",
			"grant_types_supported": []any{"authorization_code",
				"client_credentials",
				"refresh_token"},
			"id_token_signing_alg_values_supported": []any{"EdDSA"},
			"introspection_endpoint":                "http://localhost:3000/api/auth/oauth2/introspect",
			"introspection_endpoint_auth_methods_supported": []any{"client_secret_basic",
				"client_secret_post"},
			"issuer":   "http://localhost:3000/api/auth",
			"jwks_uri": "http://localhost:3000/api/auth/jwks",
			"prompt_values_supported": []any{"login",
				"consent",
				"create",
				"select_account",
				"none"},
			"registration_endpoint":    "http://localhost:3000/api/auth/oauth2/register",
			"response_modes_supported": []any{"query"},
			"response_types_supported": []any{"code"},
			"revocation_endpoint":      "http://localhost:3000/api/auth/oauth2/revoke",
			"revocation_endpoint_auth_methods_supported": []any{"client_secret_basic",
				"client_secret_post"},
			"scopes_supported":        []any{"email"},
			"subject_types_supported": []any{"public"},
			"token_endpoint":          "http://localhost:3000/api/auth/oauth2/token",
			"token_endpoint_auth_methods_supported": []any{"client_secret_basic",
				"client_secret_post"},
			"userinfo_endpoint": "http://localhost:3000/api/auth/oauth2/userinfo"}}},
}
var querySerializationCases = []querySerializationCase{{Title: "reads the signed query issue time when present", Observation: querySerializationObservation{Operation: "getSignedQueryIssuedAt", Input: querySerializationInput{Query: "client_id=abc&ba_iat=1777026004123"},
	Output: querySerializationOutput{IsDate: true, EpochMS: pointerTo(int64(1777026004123))}}},
	{Title: "returns null when ba_iat is absent", Observation: querySerializationObservation{Operation: "getSignedQueryIssuedAt", Input: querySerializationInput{Query: "client_id=abc&exp=1777026604"},
		Output: querySerializationOutput{IsNull: true}}},
	{Title: "returns null when ba_iat is not a positive finite number", Observation: querySerializationObservation{Operation: "getSignedQueryIssuedAt", Input: querySerializationInput{Query: "client_id=abc&ba_iat=not-a-number"},
		Output: querySerializationOutput{IsNull: true}}},
	{Title: "deletes the prompt key when the last value is removed", Observation: querySerializationObservation{Operation: "removePromptFromQuery", Input: querySerializationInput{Query: "client_id=abc&prompt=consent&scope=openid", Prompt: "consent"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"scope\":\"openid\"}"), OriginalQuery: "client_id=abc&prompt=consent&scope=openid", SerializedResult: "client_id=abc&scope=openid"}}},
	{Title: "does not mutate the original query", Observation: querySerializationObservation{Operation: "removePromptFromQuery", Input: querySerializationInput{Query: "client_id=abc&prompt=login+consent&scope=openid", Prompt: "login"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"prompt\":\"consent\",\"scope\":\"openid\"}"), OriginalQuery: "client_id=abc&prompt=login+consent&scope=openid", SerializedResult: "client_id=abc&prompt=consent&scope=openid"}}},
	{Title: "does nothing when the prompt value is not present", Observation: querySerializationObservation{Operation: "removePromptFromQuery", Input: querySerializationInput{Query: "client_id=abc&prompt=consent", Prompt: "login"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"prompt\":\"consent\"}"), OriginalQuery: "client_id=abc&prompt=consent", SerializedResult: "client_id=abc&prompt=consent"}}},
	{Title: "preserves multi-valued params through prompt deletion", Observation: querySerializationObservation{Operation: "removePromptFromQuery", Input: querySerializationInput{Query: "client_id=abc&prompt=login+consent&resource=https%3A%2F%2Fapi.example.com&resource=https%3A%2F%2Fother.example.com", Prompt: "login"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"prompt\":\"consent\",\"resource\":[\"https://api.example.com\",\"https://other.example.com\"]}"), OriginalQuery: "client_id=abc&prompt=login+consent&resource=https%3A%2F%2Fapi.example.com&resource=https%3A%2F%2Fother.example.com", SerializedResult: "client_id=abc&prompt=consent&resource=https%3A%2F%2Fapi.example.com&resource=https%3A%2F%2Fother.example.com"}}},
	{Title: "removes a prompt value and preserves other params", Observation: querySerializationObservation{Operation: "removePromptFromQuery", Input: querySerializationInput{Query: "client_id=abc&prompt=login+consent&scope=openid", Prompt: "login"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"prompt\":\"consent\",\"scope\":\"openid\"}"), OriginalQuery: "client_id=abc&prompt=login+consent&scope=openid", SerializedResult: "client_id=abc&prompt=consent&scope=openid"}}},
	{Title: "handles a mix of single and multi-valued params", Observation: querySerializationObservation{Operation: "searchParamsToQuery", Input: querySerializationInput{Query: "client_id=abc&resource=https%3A%2F%2Fapi.example.com&resource=https%3A%2F%2Fother.example.com&scope=openid+profile"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"resource\":[\"https://api.example.com\",\"https://other.example.com\"],\"scope\":\"openid profile\"}")}}},
	{Title: "handles empty params", Observation: querySerializationObservation{Operation: "searchParamsToQuery", Output: querySerializationOutput{Query: json.RawMessage("{}")}}},
	{Title: "preserves multi-valued params as arrays", Observation: querySerializationObservation{Operation: "searchParamsToQuery", Input: querySerializationInput{Query: "resource=https%3A%2F%2Fapi.example.com&resource=https%3A%2F%2Fother.example.com"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"resource\":[\"https://api.example.com\",\"https://other.example.com\"]}")}}},
	{Title: "preserves single-valued params as strings", Observation: querySerializationObservation{Operation: "searchParamsToQuery", Input: querySerializationInput{Query: "client_id=abc&scope=openid"},
		Output: querySerializationOutput{Query: json.RawMessage("{\"client_id\":\"abc\",\"scope\":\"openid\"}")}}}}
var revokeJWTErrorCases = []revokeJWTErrorCase{{Title: "valid no-kid", Status: 200},
	{Title: "tampered signature", Status: 500, WireError: "INTERNAL_SERVER_ERROR"},
	{Title: "wrong audience", Status: 500, WireError: "INTERNAL_SERVER_ERROR"},
	{Title: "wrong issuer", Status: 500, WireError: "INTERNAL_SERVER_ERROR"},
	{Title: "expired", Status: 200},
	{Title: "non-object JWT claims set", Status: 200},
	{Title: "non-JWT", Status: 400, WireError: "invalid_request"},
	{Title: "malformed protected header", Status: 400, WireError: "invalid_request"},
	{Title: "invalid compact JWS signature encoding", Status: 400, WireError: "invalid_request"}}
var revokeCases = []revokeCase{{Title: "should pass with the correct opaqueAccessTokenPrefix", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true, TokenStartsWithConfiguredPrefix: pointerTo(true)}},
	{Title: "should pass with the correct refreshTokenPrefix", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true, TokenStartsWithConfiguredPrefix: pointerTo(true)}},
	{Title: "should fail unauthenticated request", Observation: revokeObservation{Status: 401, DataIsNull: true}},
	{Title: "should fail verification with token_type_hint refresh_token and sent access_token", Observation: revokeObservation{Status: 400, DataIsNull: true}},
	{Title: "should fail with token_type_hint access_token and sent refresh_token", Observation: revokeObservation{Status: 400, DataIsNull: true}},
	{Title: "should pass verification with token_type_hint access_token and sent jwt access_token", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true}},
	{Title: "should pass verification with token_type_hint access_token and sent opaque access_token", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true}},
	{Title: "should pass verification with token_type_hint refresh_token and sent refresh_token", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true}},
	{Title: "should pass verification without token_type_hint and sent jwt access_token", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true}},
	{Title: "should pass verification without token_type_hint and sent opaque access_token", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true}},
	{Title: "should pass verification without token_type_hint and sent refresh_token", Observation: revokeObservation{Status: 200, DataIsNull: true, ErrorIsNull: true}}}
var safeURLCases = []safeURLCase{{Title: "should accept custom schemes for mobile apps", Observation: safeURLExpectation{Input: "myapp://oauth/callback", Success: true, MessageContains: []string{}}},
	{Title: "should reject data: scheme", Observation: safeURLExpectation{Input: "data:text/html,<script>", MessageContains: []string{"data:"}}},
	{Title: "should reject javascript: scheme", Observation: safeURLExpectation{Input: "javascript:alert(1)", MessageContains: []string{"javascript:"}}},
	{Title: "should reject vbscript: scheme", Observation: safeURLExpectation{Input: "vbscript:msgbox", MessageContains: []string{"vbscript:"}}},
	{Title: "should accept HTTP [::1] (IPv6 localhost)", Observation: safeURLExpectation{Input: "http://[::1]:3000/callback", Success: true, MessageContains: []string{}}},
	{Title: "should accept HTTP 127.0.0.1", Observation: safeURLExpectation{Input: "http://127.0.0.1:8080/callback", Success: true, MessageContains: []string{}}},
	{Title: "should accept HTTP localhost", Observation: safeURLExpectation{Input: "http://localhost:3000/api/auth/callback", Success: true, MessageContains: []string{}}},
	{Title: "should accept HTTPS URLs", Observation: safeURLExpectation{Input: "https://example.com/callback", Success: true, MessageContains: []string{}}},
	{Title: "should reject HTTP 127.0.0.1.evil.com (subdomain attack)", Observation: safeURLExpectation{Input: "http://127.0.0.1.evil.com/callback", MessageContains: []string{}}},
	{Title: "should reject HTTP for IP addresses other than 127.0.0.1", Observation: safeURLExpectation{Input: "http://192.168.1.1/callback", MessageContains: []string{}}},
	{Title: "should reject HTTP for non-localhost domains", Observation: safeURLExpectation{Input: "http://example.com/callback", MessageContains: []string{"HTTPS"}}},
	{Title: "should reject HTTP localhost.evil.com (subdomain attack)", Observation: safeURLExpectation{Input: "http://localhost.evil.com/callback", MessageContains: []string{}}},
	{Title: "should reject empty strings", Observation: safeURLExpectation{MessageContains: []string{}}},
	{Title: "should reject invalid URLs", Observation: safeURLExpectation{Input: "not-a-valid-url", MessageContains: []string{}}}}
var oauthProviderSchemaCases = []oauthProviderSchemaCase{{Title: "indexes OAuth foreign-key fields", Observations: []oauthProviderSchemaObservation{oauthProviderSchemaObservation{Model: "oauthClient", Field: "userId", Index: true, ReferencesDefined: true, References: struct {
	Model    string "json:\"model\""
	Field    string "json:\"field\""
	OnDelete string "json:\"onDelete\""
}{Model: "user", Field: "id"}},
	oauthProviderSchemaObservation{Model: "oauthRefreshToken", Field: "clientId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "oauthClient", Field: "clientId"}},
	oauthProviderSchemaObservation{Model: "oauthRefreshToken", Field: "sessionId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "session", Field: "id", OnDelete: "set null"}},
	oauthProviderSchemaObservation{Model: "oauthRefreshToken", Field: "userId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "user", Field: "id"}},
	oauthProviderSchemaObservation{Model: "oauthAccessToken", Field: "clientId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "oauthClient", Field: "clientId"}},
	oauthProviderSchemaObservation{Model: "oauthAccessToken", Field: "sessionId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "session", Field: "id", OnDelete: "set null"}},
	oauthProviderSchemaObservation{Model: "oauthAccessToken", Field: "userId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "user", Field: "id"}},
	oauthProviderSchemaObservation{Model: "oauthAccessToken", Field: "refreshId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "oauthRefreshToken", Field: "id"}},
	oauthProviderSchemaObservation{Model: "oauthConsent", Field: "clientId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "oauthClient", Field: "clientId"}},
	oauthProviderSchemaObservation{Model: "oauthConsent", Field: "userId", Index: true, ReferencesDefined: true, References: struct {
		Model    string "json:\"model\""
		Field    string "json:\"field\""
		OnDelete string "json:\"onDelete\""
	}{Model: "user", Field: "id"}}}}}
var signedQueryCases = []signedQueryCase{{Title: "builds oauth_query from declared signed params", Observation: signedQueryObservation{Operation: "build", Input: signedQueryInput{BaseEntries: [][]string{[]string{"client_id",
	"client-a"},
	[]string{"custom_authorization_context",
		"tenant-a"},
	[]string{"resource",
		"https://api.example.com"},
	[]string{"exp",
		"123"}},
	Search: "?sig=test-sig&ba_param=resource&ba_param=exp&ba_param=custom_authorization_context&ba_param=client_id&ba_param=ba_param&exp=123&resource=https%3A%2F%2Fapi.example.com&custom_authorization_context=tenant-a&client_id=client-a&utm_email=user%40example.com"},
	Output: signedQueryOutput{SignedParameterNames: []string{"ba_param",
		"client_id",
		"custom_authorization_context",
		"exp",
		"resource"},
		Result: "sig=test-sig&ba_param=resource&ba_param=exp&ba_param=custom_authorization_context&ba_param=client_id&ba_param=ba_param&exp=123&resource=https%3A%2F%2Fapi.example.com&custom_authorization_context=tenant-a&client_id=client-a", CustomAuthorizationContext: pointerTo("tenant-a"), Resource: pointerTo("https://api.example.com"), DeclaresCustomAuthorizationContext: true}}},
	{Title: "canonicalizes repeated params by key and value", Observation: signedQueryObservation{Operation: "canonicalize", Input: signedQueryInput{Entries: [][]string{[]string{"resource",
		"https://b.example.com"},
		[]string{"client_id",
			"client-a"},
		[]string{"resource",
			"https://a.example.com"}}},
		Output: signedQueryOutput{Result: "client_id=client-a&resource=https%3A%2F%2Fa.example.com&resource=https%3A%2F%2Fb.example.com"}}},
	{Title: "ignores legacy signed queries without declared signed params", Observation: signedQueryObservation{Operation: "legacy", Input: signedQueryInput{Search: "?client_id=client-a&sig=test-sig"}}}}
var timestampCases = []timestampCase{{Title: "parses epoch-millis text values", Observations: []timestampObservation{timestampObservation{Operation: "normalize", Label: "numeric text", Input: timestampInput{Kind: "json", Value: json.RawMessage("\"1774295570569.0\"")},
	Output: timestampOutput{Defined: true, IsDate: true, EpochMS: pointerTo(int64(1774295570569))}}}},
	{Title: "returns undefined for invalid values", Observations: []timestampObservation{timestampObservation{Operation: "normalize", Label: "invalid date text", Input: timestampInput{Kind: "json", Value: json.RawMessage("\"not-a-date\"")}},
		timestampObservation{Operation: "normalize", Label: "NaN", Input: timestampInput{Kind: "nan"}},
		timestampObservation{Operation: "normalize", Label: "out-of-range number", Input: timestampInput{Kind: "json", Value: json.RawMessage("9000000000000000")}},
		timestampObservation{Operation: "normalize", Label: "out-of-range numeric text", Input: timestampInput{Kind: "json", Value: json.RawMessage("\"9e15\"")}}}},
	{Title: "does not fall back to updatedAt timestamps", Observations: []timestampObservation{timestampObservation{Operation: "resolve", Label: "direct updatedAt", Input: timestampInput{Kind: "json", Value: json.RawMessage("{\"updatedAt\":1774295570569}")}},
		timestampObservation{Operation: "resolve", Label: "nested updated_at", Input: timestampInput{Kind: "json", Value: json.RawMessage("{\"session\":{\"updated_at\":\"1774295570569.0\"}}")}}}},
	{Title: "normalizes direct Date values", Observations: []timestampObservation{timestampObservation{Operation: "resolve", Label: "direct Date", Input: timestampInput{Kind: "date", EpochMS: pointerTo(int64(1774295570569))},
		Output: timestampOutput{Defined: true, IsDate: true, EpochMS: pointerTo(int64(1774295570569))}}}},
	{Title: "reads createdAt from direct session objects", Observations: []timestampObservation{timestampObservation{Operation: "resolve", Label: "direct createdAt", Input: timestampInput{Kind: "json", Value: json.RawMessage("{\"createdAt\":\"1774295570569.0\"}")},
		Output: timestampOutput{Defined: true, IsDate: true, EpochMS: pointerTo(int64(1774295570569))}}}},
	{Title: "reads created_at from nested session payloads", Observations: []timestampObservation{timestampObservation{Operation: "resolve", Label: "nested created_at", Input: timestampInput{Kind: "json", Value: json.RawMessage("{\"session\":{\"created_at\":1774295570569}}")},
		Output: timestampOutput{Defined: true, IsDate: true, EpochMS: pointerTo(int64(1774295570569))}}}}}
var userInfoCases = []userInfoCase{{Title: "should accept POST with the bearer token in the Authorization header", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"email",
	"email_verified",
	"family_name",
	"given_name",
	"name",
	"sub"},
	SubMatches: true, NameMatches: true, GivenNameType: "string", FamilyNameType: "string", EmailMatches: true, EmailVerifiedMatches: true}},
	{Title: "should fail unauthenticated request", Observation: userInfoObservation{Status: 401}},
	{Title: "should fail without the openid scope", Observation: userInfoObservation{Status: 400}},
	{Title: "should pass provide all user information - jwt", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"email",
		"email_verified",
		"family_name",
		"given_name",
		"name",
		"sub"},
		SubMatches: true, NameMatches: true, GivenNameType: "string", FamilyNameType: "string", EmailMatches: true, EmailVerifiedMatches: true}},
	{Title: "should pass provide all user information - opaque", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"email",
		"email_verified",
		"family_name",
		"given_name",
		"name",
		"sub"},
		SubMatches: true, NameMatches: true, GivenNameType: "string", FamilyNameType: "string", EmailMatches: true, EmailVerifiedMatches: true}},
	{Title: "should pass provide scoped user information - email only", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"email",
		"email_verified",
		"sub"},
		SubMatches: true, GivenNameType: "undefined", FamilyNameType: "undefined", EmailMatches: true, EmailVerifiedMatches: true}},
	{Title: "should pass provide scoped user information - profile only", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"family_name",
		"given_name",
		"name",
		"sub"},
		SubMatches: true, NameMatches: true, GivenNameType: "string", FamilyNameType: "string"}},
	{Title: "should pass provide scoped user information - sub only", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"sub"},
		SubMatches: true, GivenNameType: "undefined", FamilyNameType: "undefined"}},
	{Title: "should reject auth.api userinfo when Authorization header is missing", Observation: userInfoObservation{Status: 401, Error: "invalid_request", ErrorDescription: "authorization header not found"}},
	{Title: "should return userinfo via auth.api with headers only (no Request)", Observation: userInfoObservation{Status: 200, ClaimKeys: []string{"email",
		"email_verified",
		"family_name",
		"given_name",
		"name",
		"sub"},
		SubMatches: true, NameMatches: true, GivenNameType: "string", FamilyNameType: "string", EmailMatches: true, EmailVerifiedMatches: true}}}
