package storage_test

var adapterFactoryE2EScenarios = []adapterFactoryE2ETest{
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom map input and output key transformation"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom map input key transformation"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom map output key transformation"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom transform input"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom transform input and output"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom transform input to transform the where clause"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should allow custom transform output"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should expect the fields to be transformed into the correct field names if customized"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should expect the model to be transformed into the correct model name if customized"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should expect the result to follow the schema"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should expect the result to respect the select fields"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should fill in the missing fields in the result"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should include an \"id\" in the result in all cases, unless \"select\" is used to exclude it"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should modify boolean type to 1 or 0 if the DB doesn't support it. And expect the result to be transformed back to boolean"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should modify date type to TEXT if the DB doesn't support it. And expect the result to be transformed back to date"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should modify JSON type to TEXT if the DB doesn't support it. And expect the result to be transformed back to JSON"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should modify number[] type to TEXT if the DB doesn't support it. And expect the result to be transformed back to number[]"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should modify string[] type to TEXT if the DB doesn't support it. And expect the result to be transformed back to string[]"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should not modify result null to string for id or fields referencing id"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "should not return string for nullable foreign keys"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > create", Title: "Should receive a generated id during the call, unless \"disableIdGeneration\" is set to true"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > find", Title: "findMany: Should receive an integer id in where clause if the user has enabled `serial`"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > find", Title: "findMany: Should transform the where clause according to the schema"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > find", Title: "findOne: Should receive an integer id in where clause if the user has enabled `serial`"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > find", Title: "findOne: Should transform the where clause according to the schema"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should allow custom map input and output key transformation"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should allow custom map input key transformation"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should allow custom map output key transformation"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should allow custom transform input"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should allow custom transform input and output"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should allow custom transform output"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should expect not to receive an id even if disableIdGeneration is false in an update call"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should expect the fields to be transformed into the correct field names if customized"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should fill in the missing fields in the result"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should include an \"id\" in the result in all cases"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should modify boolean type to 1 or 0 if the DB doesn't support it. And expect the result to be transformed back to boolean"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should modify date type to TEXT if the DB doesn't support it. And expect the result to be transformed back to date"},
	{Suite: "Create Adapter Helper > Checking for the results of an adapter call, as well as the parameters passed into the adapter call > update", Title: "Should modify JSON type to TEXT if the DB doesn't support it. And expect the result to be transformed back to JSON"},
	{Suite: "Create Adapter Helper", Title: "Should generate UUIDs when `advanced.database.generateId` is set to 'uuid'"},
	{Suite: "Create Adapter Helper", Title: "Should have the correct adapter id"},
	{Suite: "Create Adapter Helper", Title: "Should not generate an id if `advanced.database.generateId` is not defined or false"},
	{Suite: "Create Adapter Helper", Title: "Should preserve a forced UUID when the adapter supports native UUIDs"},
	{Suite: "Create Adapter Helper", Title: "Should use the id generator if passed into the adapter config"},
	{Suite: "Fallback JoinOption System > Default behavior (supportsJoin not specified)", Title: "Should default to supportsJoin: false and use fallback join system"},
	{Suite: "Fallback JoinOption System > supportsJoin: false (Fallback mode)", Title: "findMany: Should handle forward joins efficiently using IN operator"},
	{Suite: "Fallback JoinOption System > supportsJoin: false (Fallback mode)", Title: "findMany: Should not pass join to adapter when supportsJoin is false"},
	{Suite: "Fallback JoinOption System > supportsJoin: false (Fallback mode)", Title: "findOne: Should handle forward joins (joined model has FK to base model) by making separate queries"},
	{Suite: "Fallback JoinOption System > supportsJoin: false (Fallback mode)", Title: "findOne: Should not pass join to adapter when supportsJoin is false"},
	{Suite: "Fallback JoinOption System > supportsJoin: true (Native join support)", Title: "findMany: Should pass join to adapter when supportsJoin is true"},
	{Suite: "Fallback JoinOption System > supportsJoin: true (Native join support)", Title: "findOne: Should pass join to adapter when supportsJoin is true"},
}
