// Package postgres implements the single-auth storage contract on top of an
// already opened PostgreSQL database/sql handle. It deliberately imports no
// concrete PostgreSQL driver; the caller owns and closes the handle.
package postgres

import (
	"crypto/rand"
	"encoding/hex"
	"fmt"
	"time"

	"github.com/pers0na2dev/single-auth/storage"
)

// IDGenerator creates a canonical identifier for a model.
type IDGenerator func(model string) (any, error)

// IDType selects the physical PostgreSQL primary-key representation.
type IDType string

const (
	// TextID stores generated identifiers in TEXT columns.
	TextID IDType = "text"
	// UUIDID stores identifiers in native UUID columns.
	UUIDID IDType = "uuid"
	// SerialID uses INTEGER GENERATED BY DEFAULT AS IDENTITY. Missing IDs are
	// omitted from INSERT and generated by PostgreSQL.
	SerialID IDType = "serial"

	defaultDatabaseSchema = "public"
)

// Options configure an Adapter. A zero Schema selects storage.CoreSchema and
// a zero DefaultFindManyLimit selects reference implementation's default of 100.
type Options struct {
	Schema storage.Schema
	// DatabaseSchema is the PostgreSQL namespace for unqualified model names.
	// The zero value selects public. A ModelName in schema.table form overrides
	// this default for that model; both parts are always quoted separately.
	DatabaseSchema       string
	IDGenerator          IDGenerator
	IDType               IDType
	Clock                func() time.Time
	DefaultFindManyLimit int
}

type config struct {
	schema         storage.Schema
	databaseSchema string
	idGenerator    IDGenerator
	clock          func() time.Time
	defaultLimit   int
	idType         IDType
	databaseID     bool
	capabilities   storage.Capabilities
}

func normalizeOptions(options Options) (config, error) {
	schema := options.Schema
	if len(schema.Models) == 0 {
		schema = storage.CoreSchema()
	}
	schema = schema.Clone()
	if err := schema.Validate(); err != nil {
		return config{}, fmt.Errorf("postgres: schema: %w", err)
	}
	if err := validateReservedNames(schema); err != nil {
		return config{}, err
	}
	databaseSchema := options.DatabaseSchema
	if databaseSchema == "" {
		databaseSchema = defaultDatabaseSchema
	}
	if err := validatePostgresIdentifier("schema", databaseSchema); err != nil {
		return config{}, err
	}

	defaultLimit := options.DefaultFindManyLimit
	if defaultLimit == 0 {
		defaultLimit = 100
	}
	if defaultLimit < 0 {
		return config{}, fmt.Errorf("postgres: default limit must be non-negative")
	}
	idGenerator := options.IDGenerator
	idType := options.IDType
	if idType == "" {
		idType = TextID
	}
	if idType != TextID && idType != UUIDID && idType != SerialID {
		return config{}, fmt.Errorf("postgres: unsupported ID type %q", idType)
	}
	databaseID := idType == SerialID || (idType == UUIDID && idGenerator == nil)
	if idGenerator == nil && !databaseID {
		idGenerator = randomID
	}
	clock := options.Clock
	if clock == nil {
		clock = time.Now
	}

	capabilities := storage.NativeCapabilities()
	capabilities.NumericIDs = idType == SerialID
	// PostgreSQL stores JSON natively. codec.go still binds canonical JSON as
	// text so both pgx and lib/pq work without driver-specific wrappers.
	capabilities.JSON = true
	capabilities.Arrays = false
	capabilities.SchemaCreation = true

	return config{
		schema:         schema,
		databaseSchema: databaseSchema,
		idGenerator:    idGenerator,
		clock:          clock,
		defaultLimit:   defaultLimit,
		idType:         idType,
		databaseID:     databaseID,
		capabilities:   capabilities,
	}, nil
}

func randomID(string) (any, error) {
	buffer := make([]byte, 16)
	if _, err := rand.Read(buffer); err != nil {
		return nil, fmt.Errorf("postgres: generate ID: %w", err)
	}
	return hex.EncodeToString(buffer), nil
}
