package cookies

import (
	"sort"
	"strconv"
	"strings"
)

const (
	MaxCookieSize   = 4050
	MaxCookieChunks = 100
)

// Chunk is one cookie write generated by Store.
type Chunk struct {
	Name    string
	Value   string
	Options Options
}

// Store performs the reference implementation compatible cache-cookie chunking and cleanup.
type Store struct {
	storeName  string
	cookieName string
	options    Options
	existing   []Pair
	warn       func(string)
}

// NewStore creates a chunking store from the incoming Cookie header.
func NewStore(storeName, cookieName string, options Options, incomingCookieHeader string, warn func(string)) *Store {
	parsed := Parse(incomingCookieHeader)
	existing := make([]Pair, 0)
	for _, pair := range parsed.Pairs() {
		if strings.HasPrefix(pair.Name, cookieName) {
			existing = append(existing, pair)
		}
	}
	return &Store{
		storeName:  storeName,
		cookieName: cookieName,
		options:    options,
		existing:   existing,
		warn:       warn,
	}
}

// ChunkValue expires stale chunks and emits either one cookie or numbered
// chunks. Oversized values are skipped after stale chunks are expired.
func (s *Store) ChunkValue(value string, overrides *Options) []Chunk {
	options := s.options
	if overrides != nil {
		options = mergeOptions(options, *overrides)
	}
	result := s.Clean()
	chunkSize := MaxCookieSize - len(Serialize(s.cookieName+"."+strconv.Itoa(MaxCookieChunks-1), "", options))
	if chunkSize <= 0 {
		s.warnTooLarge()
		return result
	}
	count := (len(value) + chunkSize - 1) / chunkSize
	if count <= 1 {
		return append(result, Chunk{Name: s.cookieName, Value: value, Options: options})
	}
	if count > MaxCookieChunks {
		s.warnTooLarge()
		return result
	}
	for index := 0; index < count; index++ {
		start := index * chunkSize
		end := start + chunkSize
		if end > len(value) {
			end = len(value)
		}
		result = append(result, Chunk{
			Name:    s.cookieName + "." + strconv.Itoa(index),
			Value:   value[start:end],
			Options: options,
		})
	}
	return result
}

// Clean returns deletion writes for every current bare/chunked cookie.
func (s *Store) Clean() []Chunk {
	if len(s.existing) == 0 {
		return nil
	}
	zero := 0
	options := s.options
	options.MaxAge = &zero
	result := make([]Chunk, 0, len(s.existing))
	for _, pair := range s.existing {
		result = append(result, Chunk{Name: pair.Name, Value: "", Options: options})
	}
	s.existing = nil
	return result
}

func (s *Store) warnTooLarge() {
	if s.warn != nil {
		s.warn(s.storeName + " cookie is too large to store even after chunking, so the cache was skipped. Reduce the cached data or use a database session.")
	}
}

// GetChunked returns a bare cookie first, otherwise joins numbered chunks.
func GetChunked(header, cookieName string) (string, bool) {
	parsed := Parse(header)
	if value, ok := parsed.Get(cookieName); ok && value != "" {
		return value, true
	}
	type indexed struct {
		index int
		value string
	}
	chunks := make([]indexed, 0)
	for _, pair := range parsed.Pairs() {
		if !strings.HasPrefix(pair.Name, cookieName+".") {
			continue
		}
		lastDot := strings.LastIndexByte(pair.Name, '.')
		index, ok := parseLeadingInt(pair.Name[lastDot+1:])
		if ok {
			chunks = append(chunks, indexed{index: index, value: pair.Value})
		}
	}
	if len(chunks) == 0 {
		return "", false
	}
	sort.SliceStable(chunks, func(i, j int) bool { return chunks[i].index < chunks[j].index })
	var builder strings.Builder
	for _, chunk := range chunks {
		builder.WriteString(chunk.value)
	}
	return builder.String(), true
}

func mergeOptions(base, override Options) Options {
	// Options intentionally has concrete fields. A non-zero override matches
	// the Partial<CookieOptions> values used by the reference implementation call sites.
	if override.MaxAge != nil {
		base.MaxAge = override.MaxAge
	}
	if override.Expires != nil {
		base.Expires = override.Expires
	}
	if override.Domain != "" {
		base.Domain = override.Domain
	}
	if override.Path != "" {
		base.Path = override.Path
	}
	if override.SameSite != "" {
		base.SameSite = override.SameSite
	}
	if override.Secure {
		base.Secure = true
	}
	if override.HTTPOnly {
		base.HTTPOnly = true
	}
	if override.Partitioned {
		base.Partitioned = true
	}
	return base
}
